fkie-cad/FACT_core

- src/test/common_helper.py
Opens the possibility of using (and testing) database access in analysis plugins
> Added public collections to DatabaseMock

- pytest.ini
- src/test/common_helper.py
- src/test/unit/analysis/analysis_plugin_test_class.py
- src/test/unit/web_interface/base.py
Another string of fixes. Now really catching all cases used in private plugins. Also fixing a test broken by the last merge.
> Test helper improvement

- install.py
- src/statistic/update.py
- src/update_variety_data.py
- src/web_interface/templates/database/database_advanced_search.html
> 13 create variety data takes too long

- src/statistic/work_load.py
- src/web_interface/templates/system_health.html
> #17: system version added to health page

- src/web_interface/templates/upload/upload.html
New feature: device names are now sorted on the upload page.
Refers to internal issue 34 "Device Names not sorted on Upload page".
> sorted device names on upload page

- src/helperFunctions/file_tree.py
- src/storage/db_interface_frontend.py
- src/test/unit/helperFunctions/test_file_tree.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/templates/about.html
- src/web_interface/templates/show_analysis.html
> 45 file tree bug

- src/test/acceptance/test_stats_and_system_monitor.py
Acceptance test for workload statistic
> system monitor test added

- src/plugins/compare/file_coverage/view/file_coverage.html
- src/storage/db_interface_compare.py
- src/test/acceptance/base.py
- src/test/acceptance/rest/test_rest_analyze_firmware.py
- src/test/acceptance/rest/test_rest_compare.py
- src/test/acceptance/rest/test_rest_download.py
- src/test/acceptance/test_analyze_firmware.py
- src/test/acceptance/test_compare_firmwares.py
- src/test/acceptance/test_file_download.py
- src/test/acceptance/test_stats_and_system_monitor.py
- src/test/integration/intercom/test_intercom_common.py
- src/test/integration/intercom/test_task_communication.py
- src/test/integration/scheduler/test_unpack_analyse_and_compare.py
- src/test/integration/statistic/test_update.py
- src/test/integration/storage/test_db_interface_compare.py
- src/web_interface/components/compare_routes.py
Addresses Issue https://github.com/fkie-cad/FACT_core/issues/61 and includes more test speedups.
> 61 file compare view bug

- src/scheduler/Analysis.py
- src/test/unit/scheduler/test_analysis.py
- src/web_interface/components/statistic_routes.py
- src/web_interface/templates/system_health.html
Addresses issue https://github.com/fkie-cad/FACT_core/issues/31
> added versions to system health page

- src/compare/compare.py
- src/plugins/compare/file_header/code/file_header.py
- src/plugins/compare/file_header/test/test_file_header.py
- src/plugins/compare/file_header/view/file_header.html
- src/test/unit/compare/test_compare.py
- src/test/unit/scheduler/test_compare.py
- src/test/unit/web_interface/test_additional_functions.py
- src/web_interface/components/additional_functions/hex_dump.py
New compare plugin providing a "binwalk -Ww"-ish view on the first 512 byte block of all compared files
> Add file header plugin

- src/bootstrap/bootstrap_common.sh
- src/bootstrap/bootstrap_db.sh
- src/plugins/unpacking/squashFS/install.sh
> apt -> apt-get

- src/web_interface/templates/add_comment.html
addresses [User Authentication -> Comment User Autofill #89](https://github.com/fkie-cad/FACT_core/issues/89)
> added user name to comment page for authenticated users

- .gitignore
- src/bootstrap/bootstrap_frontend.sh
- src/helperFunctions/web_interface.py
- src/test/unit/test_user_role_db_interface.py
- src/test/unit/web_interface/test_app_user_management_routes.py
- src/test/unit/web_interface/test_filter.py
- src/web_interface/components/component_base.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/components/user_management_routes.py
- src/web_interface/filter.py
- src/web_interface/frontend_main.py
- src/web_interface/security/authentication.py
- src/web_interface/security/privileges.py
- src/web_interface/security/user_role_db_interface.py
- src/web_interface/templates/base.html
- src/web_interface/templates/user_management/edit_user.html
- src/web_interface/templates/user_management/manage_users.html
- src/web_interface/templates/user_management/user_profile.html
> 97 user management gui

- src/analysis/PluginBase.py
- src/plugins/analysis/software_components/code/software_components.py
- src/plugins/analysis/software_components/install.sh
- src/plugins/analysis/software_components/internal/install.py
- src/plugins/analysis/software_components/internal/scan_signatures.py
- src/plugins/analysis/software_components/signatures/os.yara
- src/plugins/analysis/software_components/test/data/test_signature.yara
- src/plugins/analysis/software_components/test/test_scan_signatures.py
- Added Signature for Cisco IOS
- Added generic add tag method to PluginBase
> Added tagging of OS Information in Plugin: software components

- src/plugins/unpacking/dji/code/dji_drones.py
- src/plugins/unpacking/dji/install.sh
> dji unpacker install issue fixed

- src/test/unit/web_interface/test_filter.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/filter.py
needed for [issue 4](https://git-sdn.caad.fkie.fraunhofer.de/FACT/analysis_plugin/plugin_qemu_exec/issues/4) in the qemu_exec plugin
> added filter for decompressing compressed strace data

- src/helperFunctions/debug.py
- src/helperFunctions/hash.py
- src/test/unit/helperFunctions/test_debug.py
Tried adding a pipe_to_logging decorator as well, but that failed for unknown reasons. Test did succeed, but the messages never showed up in debug logs.
> Suppress lief stdout

- src/helperFunctions/yara_binary_search.py
- src/intercom/front_end_binding.py
- src/storage/db_interface_common.py
- src/test/common_helper.py
- src/test/data/binary_search_test/bi/binary_search_test_2
- src/test/data/binary_search_test/bi/binary_search_test_3
- src/test/integration/storage/test_db_interface.py
- src/test/unit/helperFunctions/test_yara_binary_search.py
- src/test/unit/web_interface/test_app_binary_search.py
- src/web_interface/components/database_routes.py
- src/web_interface/templates/database/database_binary_search.html
- src/web_interface/templates/show_analysis.html
> 102 binary search on single

- src/analysis/PluginBase.py
- src/analysis/YaraPluginBase.py
- src/compare/compare.py
- src/helperFunctions/fileSystem.py
- src/plugins/analysis/checksec/test/test_plugin_checksec.py
- src/plugins/analysis/crypto_material/code/crypto_material.py
- src/plugins/analysis/file_type/test/test_plugin_file_type.py
- src/plugins/analysis/ip_and_uri_finder/code/ip_and_uri_finder.py
- src/plugins/analysis/known_vulnerabilities/code/known_vulnerabilities.py
- src/plugins/analysis/software_components/code/software_components.py
- src/plugins/unpacking/tpl/code/TPWRN702N.py
- src/plugins/unpacking/tpl/code/tpltool.py
- src/plugins/unpacking/yaffs/code/yaffs.py
- src/storage/db_interface_common.py
- src/storage/db_interface_frontend.py
- src/storage/db_interface_frontend_editing.py
- src/storage/mongo_interface.py
- src/test/integration/storage/test_db_interface_frontend.py
- src/test/integration/storage/test_db_interface_frontend_editing.py
removed more unused code, added two tests for untested, unused but potentially useful functions
> Refactoring and test coverage

- src/plugins/compare/file_coverage/code/file_coverage.py
- src/plugins/compare/file_coverage/test/test_plugin_file_coverage.py
- src/storage/db_interface_compare.py
- src/test/integration/scheduler/test_unpack_analyse_and_compare.py
- src/test/unit/compare/test_compare.py
- src/web_interface/templates/upload/upload.html
see commit messages for context
> Fix bug in plugin presets

- src/intercom/back_end_binding.py
- src/storage/fs_organizer.py
- src/test/acceptance/test_upload_analyze_delete_firmware.py
- src/test/integration/intercom/test_backend_scheduler.py
- src/test/unit/storage/test_fs_organizer.py
- src/web_interface/templates/about.html
> 132 delete intercom bug

- src/bootstrap/radare/docker-compose.yml
- src/bootstrap/radare/install.sh
Fixing broken enyo reference. Also container are not started at boot time but only by frontend.
> only starting container with fronend. Fixes from webui fork

- src/helperFunctions/install.py
Packets are now installed separately so that only the installation of specific packets fail.
Not that of all other packets that are installed with the packet in question.
> handling distutils case seperately

- src/install/common.py
- src/install/frontend.py
Added highlight.js setup. Was dropped during install refactoring
> Highlight.JS Fix

- src/helperFunctions/plugin.py
Added check if plugin folder has a code folder
> plugin detection validity check added

- src/compile_custom_magic.py
- src/install/backend.py
Installation: Compare custom mime moved to stand alone script.
> installation refactored

- src/helperFunctions/fileSystem.py
- src/test/unit/helperFunctions/test_file_system.py
> issue 223 fixed

- src/plugins/analysis/qemu_exec/code/qemu_exec.py
- src/plugins/analysis/qemu_exec/test/test_plugin_qemu_exec.py
added shared object mime type to qemu exec analysis plugin mime type list because some shared objects can be executed (e.g. libc.so)
> Add shared objects to qemu exec

- src/install/frontend.py
- src/test/acceptance/test_authenticated_gui.py
- pinned dependency
- try/finally in test
> Fix authentication test

- src/scheduler/Analysis.py
- added post analysis to blacklisting feature
- renamed variable from fw_object to file_object
- cc #251
> fixing bug regarding blacklist of analysis

- src/test/acceptance/test_upload_analyze_delete_firmware.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/templates/show_analysis.html
> fix issue 250: root uid is lost when pressing self

- src/helperFunctions/mongo_config_parser.py
> fix issue 255 yaml.load deprecation warning

- src/compile_yara_signatures.py
- src/helperFunctions/process.py
- src/helperFunctions/program_setup.py
- src/helperFunctions/yara.py
- src/helperFunctions/yara_binary_search.py
- src/init_database.py
- src/install/db.py
- src/objects/file.py
- src/plugins/compare/software/code/software.py
- src/start_fact.py
- src/start_fact_backend.py
- src/start_fact_db.py
- src/start_fact_frontend.py
- src/statistic/update.py
- src/storage/MongoMgr.py
- src/storage/db_interface_compare.py
- src/test/integration/statistic/test_update.py
- src/test/unit/helperFunctions/test_yara_binary_search.py
- src/update_statistic.py
- src/update_variety_data.py
- src/web_interface/components/statistic_routes.py
- src/web_interface/filter.py
https://app.codacy.com/app/johannes.vom.dorp/FACT_core/issues
> fixed some codacy issues

- src/helperFunctions/mongo_task_conversion.py
- src/helperFunctions/yara_signature_testing.py
- src/intercom/front_end_binding.py
- src/objects/file.py
- src/test/integration/storage/test_db_interface_admin.py
- src/test/unit/analysis/analysis_plugin_test_class.py
- src/test/unit/storage/test_fs_organizer.py
- src/test/unit/unpacker/test_unpacker.py
- src/unpacker/tar_repack.py
- src/unpacker/unpack.py
- src/web_interface/templates/about.html
There are still some to broad exception warnings, but these need further investigation.
> 'faf' -> 'fact' and pylint warnings fixed

- .pre-commit-config.yaml
- src/test/acceptance/rest/test_rest_statistic.py
- src/test/common_helper.py
- src/test/unit/web_interface/rest/conftest.py
- src/test/unit/web_interface/rest/test_rest_status.py
- src/web_interface/rest/rest_base.py
- src/web_interface/rest/rest_statistic.py
- src/web_interface/templates/about.html
- mirrored system_healt enpoint for rest
- can be used to instrument FACT with respect to load monitoring
- added tests where possible
> Added statistics endpoint for rest

- src/storage/db_interface_frontend.py
- src/test/integration/storage/test_db_interface_frontend.py
unpacker "analysis result" misses when unpacker depth limit is reached. In this case NOP is popped in there as a placeholder
> fixed issue with missing unpacker data and added regression test

- src/test/common_helper.py
- src/test/unit/web_interface/test_app_ajax_routes.py
- src/web_interface/components/ajax_routes.py
> fix for broken summary links

- src/plugins/analysis/qemu_exec/docker/start_binary.py
> fix for flake8 xenial issue

- src/test/acceptance/test_search.py
- src/test/common_helper.py
- src/test/unit/web_interface/test_app_show_statistic.py
- src/web_interface/templates/show_statistic.html
> 307 fix date statistics link

- src/storage/db_interface_frontend.py
> analysis not complete bugfix

- src/analysis/PluginBase.py
- src/helperFunctions/debug.py
- src/helperFunctions/logging.py
- src/helperFunctions/parsing.py
- src/helperFunctions/process.py
- src/scheduler/Analysis.py
- src/scheduler/Compare.py
- src/scheduler/Unpacking.py
- src/test/unit/helperFunctions/test_process.py
moved similar `check_exception` functions to `helper_functions/process.py` and added a test
> Refactor check exceptions

- src/web_interface/templates/database/database_advanced_search.html
- typo
- Enrich examples for mongo syntax, and add links for more help
- add static structure information for querieable fields
> added examples and object structure

- src/analysis/YaraPluginBase.py
- src/test/data/yara_matches
- src/test/unit/analysis/test_yara_plugin_base.py
there is a bug parsing yara rules with brackets in the meta data
> fixed bug in yara rule parsing

- src/helperFunctions/file_tree.py
- src/install/frontend.py
- src/storage/db_interface_frontend.py
- src/web_interface/components/ajax_routes.py
> fix bugs in file tree + refactoring

- src/helperFunctions/file_tree.py
- src/storage/db_interface_frontend.py
- src/test/integration/storage/test_db_interface_frontend.py
- src/test/unit/helperFunctions/test_file_tree.py
- src/web_interface/components/ajax_routes.py
> file tree bugfix + refactoring

- src/test/unit/helperFunctions/test_process.py
fix for #351 
- test_check_worker_exceptions failed seemingly randomly (probably when CI was very busy)
> increased test timings

- src/storage/db_interface_frontend.py
- src/web_interface/components/ajax_routes.py
reduced db query count for children in the file tree from n to 1
> file tree speed-up

- src/plugins/analysis/cve_lookup/code/cve_lookup.py
- src/plugins/analysis/cve_lookup/internal/helper_functions.py
- src/plugins/analysis/cve_lookup/test/test_cve_lookup.py
fixed a bug where software with multiple terms in its name was not correctly matched
> fixed bug in cve_lookup

- src/plugins/analysis/elf_analysis/view/elf_analysis.html
> summary removed from view

- src/plugins/analysis/ip_and_uri_finder/view/ip_and_uri_finder.html
> fix view of ip-and-uri-finder

- src/plugins/analysis/cve_lookup/code/cve_lookup.py
- src/plugins/analysis/cve_lookup/test/test_cve_lookup.py
added tags for critical CVE matches
> added cve_lookup tags

- src/plugins/analysis/elf_analysis/code/elf_analysis.py
- src/plugins/analysis/elf_analysis/test/test_plugin_elf_analysis.py
- src/storage/db_interface_frontend.py
- bugfix for error during json conversion in elf analysis plugin
- bugfix for file tree when not all files are in the database
> Sd918 bugfix elf analysis

- src/config/main.cfg
- src/start_fact_frontend.py
solving #285 and add cve_lookup to default plug-in set
> thunder-lock activated and cve_lookup set as default plug-in

- src/statistic/update.py
- src/storage/db_interface_frontend.py
addresses  #365
added `allowDiskUse=True` to `aggregate()` calls in order to (hopefully) fix the memory problems
> 365 update statistics bugfix

- src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
- src/plugins/analysis/users_and_passwords/test/test_plugin_password_file_analyzer.py
- src/plugins/analysis/users_and_passwords/view/users_and_passwords.html
- src/storage/db_interface_view_sync.py
- src/test/unit/web_interface/test_filter.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/filter.py
add an analysis tag if users and passwords plug-in finds a password
> Sd 871 known password tag

- src/analysis/PluginBase.py
- src/helperFunctions/process.py
- src/scheduler/Analysis.py
- src/scheduler/Unpacking.py
- src/test/acceptance/rest/test_rest_statistic.py
- src/test/unit/scheduler/test_unpack.py
- src/web_interface/templates/system_health.html
- added indicators for currently running plugins to the system health page 
- this could still need some fine tuning
- works OK for plugins that take a long time to process files
- works sometimes(?) for quick plugins
- problems:
- update times are bound to block delay timings and are not very accurate
> added analysis active indicator

- src/test/unit/unpacker/test_unpacker.py
- src/unpacker/unpack.py
- added unpacker analysis entry in case unpacking was skipped because the analysis depth was reached
- added test
> added analysis info for unpacking depth

- src/plugins/analysis/architecture_detection/view/cpu_architecture.html
- src/plugins/analysis/crypto_hints/view/crypto_hints.html
- src/plugins/analysis/crypto_material/view/crypto_material.html
- src/plugins/analysis/init_systems/view/init_system.html
- src/plugins/analysis/ip_and_uri_finder/view/ip_and_uri_finder.html
- src/plugins/analysis/known_vulnerabilities/view/known_vulnerabilities.html
- src/plugins/analysis/software_components/view/software_components.html
- src/plugins/analysis/tlsh/view/tlsh.html
- src/test/unit/web_interface/test_filter.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/filter.py
- src/web_interface/templates/analysis_plugins/generic.html
- replaced `if key in [...]` with new filter `is_not_mandatory_analysis_entry` in plugin templates
> Sd 969 is not mandatory analysis entry utilization

- src/install/common.py
> fixed varietyjs installation bug

- src/storage/db_interface_frontend.py
- src/test/acceptance/test_advanced_search.py
- src/test/integration/storage/test_db_interface_frontend.py
- src/web_interface/components/database_routes.py
- fixed inverse firmware search bugs:
- direct matching firmware
- result count
- fixed/extended test
> Bugfix inverted search result count

- src/analysis/PluginBase.py
- src/analysis/YaraPluginBase.py
- src/start_fact.py
- src/start_fact_backend.py
- added error handling and shutdown for FACT if signatures are missing
> added error handling for missing singature files

- src/helperFunctions/rest.py
- src/storage/db_interface_frontend.py
- src/test/common_helper.py
- src/test/unit/helperFunctions/test_rest.py
- src/test/unit/web_interface/rest/test_rest_binary.py
- src/test/unit/web_interface/rest/test_rest_firmware.py
- src/web_interface/rest/rest_file_object.py
- src/web_interface/rest/rest_firmware.py
- added `inverse` parameter to `/rest/firmware` for inverse parent firmware search
- refactoring
> Sd 965 inverse firmware search rest

- src/plugins/analysis/software_components/code/software_components.py
- src/plugins/analysis/software_components/signatures/http_server.yara
- src/plugins/analysis/software_components/signatures/lib.yara
- src/plugins/analysis/software_components/signatures/os.yara
- src/plugins/analysis/software_components/test/data/software_component_test_list.txt
Improved Signature of ThreadX and added Signature for eCos
> Software signatures improved and added

- src/install/frontend.py
> fixed jstree reinstall bug

- src/start_fact.py
fixed bug where starting all installed FACT components with `start_fact.py` could lead to an error when the backend is not installed
> fixed start all components bug

- src/plugins/analysis/cve_lookup/code/cve_lookup.py
- src/plugins/analysis/cve_lookup/test/test_cve_lookup.py
added "(CRITICAL)" suffix to cve_lookup summary entries if one of the scores is 9.0 or higher
> added critical summary suffix + test

- src/update_variety_data.py
- removed uninteresting keys from `varietyjs` results database
> removed uninteresting keys from variety result

- src/install/frontend.py
a new version of WTForms causes a dependency problem causing the tests to fail
`sudo -EH pip3 install --upgrade WTForms`
Can be used to reproduce this issue.
> fix installation issue

- src/analysis/PluginBase.py
- src/objects/file.py
- src/scheduler/Analysis.py
- src/test/unit/scheduler/test_analysis.py
- src/web_interface/components/analysis_routes.py
- src/web_interface/templates/analysis_plugins/fail.html
- src/web_interface/templates/show_analysis.html
- added rescheduling in case of exception or timeout during an analysis 
- added `processed_analysis` entries for failed analyses and a template in the web-interface 
- added highlighting of selected analysis on the analysis page
> Experimental webinterface fail feedback

- src/web_interface/templates/base.html
- only the name in the navbar dropdown menus was "clickable" -> now it should be the whole highlighted area
- used https://getbootstrap.com/docs/4.0/components/navbar/ as reference
> fix navbar link area

- src/intercom/back_end_binding.py
- src/scheduler/Analysis.py
- src/test/integration/intercom/test_backend_scheduler.py
- src/test/unit/scheduler/test_analysis.py
- src/web_interface/templates/system_health.html
- added option to track the analysis status of all currently analyzed firmware images (incl. when all files are fully analyzed)
- added error messages for failed analyses in the web interface
> firmware analysis status

- src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
- src/plugins/analysis/users_and_passwords/test/test_plugin_password_file_analyzer.py
- src/plugins/analysis/users_and_passwords/view/users_and_passwords.html
You may use this entry to test the fix:
`apson:$6$Ph+uRn1vmQ+pA7Ka$fcn9/Ln3W6c6oT3o8bWoLPrmTUs `
> SD-1045 unsupported hash type bug fixed

- src/scheduler/Analysis.py
- src/test/unit/scheduler/test_analysis.py
- `failed` key was missing in DB query
- added test case
> Sd1047 failed analysis version check bugfix

- src/web_interface/templates/base.html
- src/web_interface/templates/database/database_browse.html
- src/web_interface/templates/generic_view/firmware_detail_tabular_field.html
- src/web_interface/templates/home.html
converted tables on pages "home" and "database_browse" to list groups
> converted lists to list groups

- src/scheduler/Analysis.py
- src/statistic/work_load.py
- src/test/acceptance/test_misc.py
- src/test/common_helper.py
- src/web_interface/filter.py
- src/web_interface/rest/rest_statistic.py
- src/web_interface/templates/show_analysis.html
- src/web_interface/templates/system_health.html
- Added plugin information to intercom object
- Replaced plugin table in sys health with plugin cards
- Replaced machine tables by more compact cards
> System health redesign

- src/storage/db_interface_frontend.py
- src/test/common_helper.py
- src/test/integration/storage/test_db_interface_frontend.py
- src/test/unit/web_interface/test_app_missing_analyses.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/components/miscellaneous_routes.py
- src/web_interface/templates/about.html
- src/web_interface/templates/find_missing_analyses.html
- src/web_interface/templates/generic_view/file_object_macros.html
- src/web_interface/templates/generic_view/nice_fo_list.html
added list of failed analyses to "missing analyses" page
> added failed analysis to missing analyses endpoint

- src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
- src/scheduler/Analysis.py
- src/test/unit/scheduler/test_analysis.py
- src/test/unit/scheduler/test_current_analyses.py
- src/test/unit/web_interface/test_filter.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/filter.py
- src/web_interface/templates/system_health.html
- added another progress bar to display the unpacking progress
- added animation style to the progress bars
- added temporary persistence for finished analyses
- (fixed error logging in password_file_analyzer)
> Sd1114 advanced firmware analysis progress

- .gitignore
- src/helperFunctions/install.py
- src/install.py
- src/install/backend.py
- src/install/common.py
- src/install/db.py
- src/install/pre_install.sh
- src/install/pre_install_fedora.sh
- src/plugins/analysis/binwalk/install.sh
- src/plugins/analysis/linter/install.sh
- src/plugins/analysis/oms/install.sh
- src/plugins/analysis/users_and_passwords/install.sh
Fedora installation working fine
> Fedora Installation

- src/test/unit/web_interface/test_app_ajax_routes.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/templates/home.html
> home status stats bugfix

- INSTALL.md
Here is a small PR that fixed a typo discovered while reading the documentation.
> Typo fixed

- src/plugins/analysis/linter/test/data/linter_test_file
- src/plugins/analysis/linter/test/test_source_code_analysis.py
> fixed linter test

- src/plugins/analysis/linter/install.sh
> linter lua install bugfix

- src/plugins/analysis/binwalk/code/binwalk.py
- src/plugins/analysis/binwalk/install.sh
Switched binwalk fork to fix entropy graph
> switched fork to fix entropy graph

- src/statistic/update.py
Unpacking stats now only count unpackers for cases where at least 1 file was unpacked
> improved unpacking stats

- docsrc/conf.py
- docsrc/modules/helperFunctions.pdf.rst
- docsrc/modules/helperFunctions.rst
- src/helperFunctions/pdf.py
- src/test/integration/helperFunctions/test_pdf.py
- src/test/unit/helperFunctions/test_pdf.py
- src/web_interface/components/io_routes.py
Added doc to pdf.py and refactored function to make more sense
> Sd1239 plugin doc vd

- docsrc/README.md
- docsrc/conf.py
- docsrc/modules/helperFunctions.mongo_task_conversion.rst
- docsrc/modules/helperFunctions.rst
- src/helperFunctions/mongo_task_conversion.py
- src/test/acceptance/run_scripts/test_run_scripts.py
- added readme for building the docs
- added helperFunctions.mongo_task_conversion module docs
> Sd1240 plugin doc js

- src/install/common.py
pinned setuptools version to fix binwalk install
> setuptools 50 bugfix

- .pylintrc
- docsrc/index.rst
- docsrc/modules/objects.file.rst
- docsrc/modules/objects.rst
- src/helperFunctions/yara_binary_search.py
- src/intercom/back_end_binding.py
- src/objects/file.py
- src/storage/db_interface_backend.py
- src/storage/db_interface_common.py
- src/storage/fsorganizer.py
- src/test/acceptance/test_upload_analyze_delete_firmware.py
- src/test/integration/intercom/test_task_communication.py
- src/test/integration/scheduler/test_unpack_analyse_and_compare.py
- src/test/integration/scheduler/test_unpack_and_analyse.py
- src/test/integration/scheduler/test_unpack_only.py
- src/test/unit/objects/test_file.py
- src/test/unit/objects/test_firmware.py
- src/test/unit/storage/test_fs_organizer.py
- src/unpacker/unpack.py
- Sphinx documentation of FileObject
- Minor changes to FileObject API
- Major pylint implications...
> Document objects

- src/plugins/analysis/cve_lookup/internal/data_parsing.py
resolves #494 
- fixed broken link
> fix cve feed link

- src/objects/file.py
- src/test/unit/objects/test_file.py
should fix the insufficient information bug when clicking on an element in the file tree of a file object comparison
> fix insufficient info bug

- src/plugins/analysis/cwe_checker/code/cwe_checker.py
- src/plugins/analysis/cwe_checker/test/test_cwe_checker.py
This PR should improve the behaviour of the *cwe_checker* plugin on errors or timeouts.
> better handling of docker or cwe_checker errors.

- src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
- src/plugins/analysis/users_and_passwords/test/test_plugin_password_file_analyzer.py
- removed password type from tag
> fixed user/pw tag

- src/plugins/analysis/cwe_checker/code/cwe_checker.py
- src/plugins/analysis/cwe_checker/test/test_cwe_checker.py
This PR updates the cwe_checker plugin to be compatible with the newest cwe_checker docker image interface.
> adjust cwe_checker plugin to new cwe_checker version

- src/install/common.py
resolves #534 
- removed deprecated python2 installation from install script
> removed python2 installation

- src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
- src/plugins/analysis/users_and_passwords/test/data/passwd_FP_test
- src/plugins/analysis/users_and_passwords/test/data/passwd_test
- src/plugins/analysis/users_and_passwords/test/test_plugin_password_file_analyzer.py
- improved unix / `/etc/shadow` password regex to reduce false positive matches
- added htpasswd and DES regexes 
- refactoring
- added test cases
> Improved password regexes

- src/storage/db_interface_frontend.py
- src/test/unit/web_interface/test_file_tree.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/file_tree/file_tree.py
- fixed a bug where if a file is in a firmware in different containers with different paths, the file was displayed in the file tree for each container with all different paths
> fixed file tree bug

- src/plugins/analysis/cve_lookup/install.sh
- src/plugins/analysis/cve_lookup/internal/data_parsing.py
- src/plugins/analysis/cve_lookup/internal/helper_functions.py
- src/plugins/analysis/cve_lookup/internal/setup_repository.py
- fixed bug where an error during the initial setup would lead to errors in all consecutive installation attempts because of a broken DB
- added retries to download attempts
- made error logging more verbose
> Sd1449 cve lookup install bugfix

- src/install/pre_install_fedora.sh
- experimental support for Fedora 32 and 33
- updated docker installation
> Fedora33 support

- src/helperFunctions/pdf.py
- src/web_interface/components/io_routes.py
https://github.com/fkie-cad/fact_pdf_report/pull/6 needs to be merged first
> removed chown from pdf report + refactoring

- src/install/backend.py
… to recent good work from @jstucke
> Remove sudoers dependency

- src/web_interface/templates/about.html
Based on merges since last release.
Command: `git shortlog --grep="Merge pull request" 3.1..HEAD`
> Updated changelog

- src/test/unit/web_interface/test_app_ajax_routes.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/templates/home.html
- "incomplete analyses" live stat is severely impacting the performance of the "home" page ("missing analyses" is not really suitable as live stat: takes ~11s on my moderately filled DB to compute)
> removed incomplete analyses from main page

- src/install/common.py
Removed lief dependency version pinning
> Removed lief dependency version pinning

- docsrc/conf.py
- docsrc/modules/helperFunctions.config.rst
- docsrc/modules/helperFunctions.hash.rst
- docsrc/modules/helperFunctions.merge_generators.rst
- docsrc/modules/helperFunctions.object_conversion.rst
- docsrc/modules/helperFunctions.plugin.rst
- docsrc/modules/helperFunctions.program_setup.rst
- docsrc/modules/helperFunctions.rst
- src/fact_base.py
- src/helperFunctions/config.py
- src/helperFunctions/hash.py
- src/helperFunctions/merge_generators.py
- src/helperFunctions/object_conversion.py
- src/helperFunctions/plugin.py
- src/helperFunctions/program_setup.py
- src/init_database.py
- src/storage/db_interface_frontend.py
- src/test/unit/helperFunctions/test_merge_generators.py
- src/test/unit/helperFunctions/test_object_conversion.py
- src/update_statistic.py
- src/update_variety_data.py
Additionally:
* I inlined `set_signals` because it was only used in one place.
* Removed `merge_generators` and replaced with `itertools.chain`
* Rewrote some functions for better readablity
Note that I did not document some oneliners becaues reading the code is as easy as reading a doc comment for them.
> Document remaining helperFunctions

- src/plugins/analysis/kernel_config/code/kernel_config.py
- src/plugins/analysis/kernel_config/install.sh
- src/plugins/analysis/kernel_config/internal/checksec_check_kernel.py
- src/plugins/analysis/kernel_config/internal/kernel_config_hardening_check.py
- src/plugins/analysis/kernel_config/test/test_kernel_config.py
- src/plugins/analysis/kernel_config/view/kernel_config.html
- src/test/unit/web_interface/test_filter.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/filter.py
Added kernel config hardening check to kernel config plugin based on [kconfig-hardened-check](https://github.com/a13xp0p0v/kconfig-hardened-check) and [linux-kernel-defence-map](https://github.com/a13xp0p0v/linux-kernel-defence-map)
> Kernel config hardening check

- .jshintrc
- src/scheduler/Analysis.py
- src/storage/MongoMgr.py
- src/storage/db_interface_statistic.py
- src/test/integration/statistic/test_update.py
- src/test/unit/scheduler/test_current_analyses.py
- src/test/unit/web_interface/test_app_ajax_routes.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/components/statistic_routes.py
- src/web_interface/static/js/system_health.js
- src/web_interface/templates/system_health.html
Changed system health page from reloading to live updates (à la AJAX)
> system health live updates

- src/install/requirements_frontend.txt
resolves #624 
- removed `Flask-API` from installed dependencies as it seems to be unused
> removed unused dependency

- src/install/frontend.py
- src/test/unit/web_interface/test_app_user_management_routes.py
- src/web_interface/components/user_management_routes.py
- src/web_interface/templates/user_management/edit_user.html
resolves #625 
- removed x-editable dependency
- added modal for changing user roles
> Remove x editable

- src/plugins/analysis/architecture_detection/code/architecture_detection.py
- src/plugins/analysis/architecture_detection/test/test_plugin_architecture_detection.py
added some missing embedded ISAs to architecture detection plugin:
- ARC
- AVR
- RISC-V
- ESP
> added ISAs to architecture detection

- src/web_interface/static/js/quick_search.js
- src/web_interface/templates/base.html
* collapse navbar icons by removing text on searchbar expansion
* increased searchbar expansion size from `300px` to `500px`
* truncate username in navbar if `len(username) > 12`
This PR is a follow-up to PR #630 that should address the remaining layout issues present in the navigation bar.
> navbar: on searchbar expansion, collapse navbar icons

- src/install/requirements_frontend.txt
- src/intercom/back_end_binding.py
- src/intercom/common_mongo_binding.py
- src/intercom/front_end_binding.py
- src/storage/binary_service.py
- src/test/acceptance/test_authenticated_gui.py
- src/test/common_helper.py
- src/test/integration/intercom/test_backend_scheduler.py
- src/test/integration/intercom/test_task_communication.py
- src/test/integration/storage/test_binary_service.py
- src/test/unit/web_interface/test_app_ajax_routes.py
- src/test/unit/web_interface/test_app_show_analysis.py
- src/test/unit/web_interface/test_hex_highlighting.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/components/hex_highlighting.py
- src/web_interface/static/js/line_numbering.js
- src/web_interface/templates/show_analysis.html
- added hex preview for files that are neither text files nor images
- added highlighting for hex output (xxd style)
- added intercom function for retrieving part of a file
> Hex preview

- src/test/unit/web_interface/test_app_show_analysis.py
- src/web_interface/components/analysis_routes.py
Closes https://github.com/fkie-cad/FACT_core/issues/670
> Don't crash when the user requests an invalid analysis

- src/scheduler/Analysis.py
- src/web_interface/components/analysis_routes.py
- src/web_interface/templates/upload/upload.html
- added option to force reanalyzing files when using "update firmware"
resolves #678
> added force option to update

- src/scheduler/Analysis.py
- src/web_interface/components/analysis_routes.py
- src/web_interface/templates/macros.html
- src/web_interface/templates/upload/upload.html
fixed bugs in the update firmware template:
- fixed bug where it was possible to submit the update form even if some `required` elements were not selected
- fixed a bug where form errors were not displayed
- fixed a bug where the "device_part" selection was empty if the device_part of the firmware was "complete"
- fixed update scheduling bug where the updated firmware data was not saved when no analysis is scheduled
> fixed bugs in update template

- src/helperFunctions/mongo_task_conversion.py
- src/test/unit/web_interface/rest/test_rest_firmware.py
- fixes a bug when a firmware is uploaded via REST without tags
- pylint fixes
resolves #684
> fixed error when there are no tags set in rest firmware put

- src/test/acceptance/base.py
- src/test/acceptance/rest/test_rest_download.py
- src/test/acceptance/test_file_download.py
- fixes two acceptance tests that only work because of side effects from other tests:
- test_run_from_upload_to_show_analysis
- test_firmware_download
- added cleanup for TempDir
- refactoring and pylint fixes
> fixed acceptance test side effects and missing tmp dir cleanup

- src/scheduler/analysis.py
- src/scheduler/analysis_status.py
- src/start_fact_backend.py
- src/test/acceptance/base.py
- src/test/integration/scheduler/test_cycle_with_tags.py
- src/test/integration/scheduler/test_regression_virtual_file_path.py
- src/test/integration/scheduler/test_unpack_analyse_and_compare.py
- src/test/integration/scheduler/test_unpack_and_analyse.py
- src/test/unit/scheduler/test_analysis.py
- src/test/unit/scheduler/test_analysis_status.py
- Refactored current analyses / introspection code out of `Analysis.py`
- Renamed `Analysis.py` PEP conforming to `analysis.py`
- Dropped boilerplate test code
> Moved introspection code

- src/plugins/analysis/software_components/docker/Dockerfile
- updated the base image of the format string resolver (software_components plugin)
- the previous base image may be susceptible to the vulnerability in log4j
> updated base image for FSR

- src/scheduler/Unpacking.py
- src/scheduler/analysis.py
- src/scheduler/analysis_status.py
- src/start_fact_backend.py
- src/test/unit/scheduler/test_analysis.py
- src/test/unit/scheduler/test_unpack.py
resolves #718 
- added thread safety precautions to `clear_recently_finished()` function
- moved workload computation from unpacking to analysis scheduler
- pylint + typo fixes
> Current analyses keyerror bugfix

- src/plugins/analysis/binwalk/code/binwalk.py
- src/plugins/analysis/binwalk/install.py
- binwalk installation with `setup.py` seems to be broken on some systems
- changed installation to use `pip`
- added error handling to binwalk plugin
> fixed binwalk installation

- src/install/requirements_common.txt
- src/plugins/analysis/qemu_exec/code/qemu_exec.py
- src/plugins/analysis/qemu_exec/test/test_plugin_qemu_exec.py
- replaced `multiprocessing.pool` with more lightweight `ThreadPoolExecutor`
- fixed missing fallback method from `BinaryService`
- added timeout to occasionally hanging tests
> Threaded qemu exec plugin

- src/plugins/analysis/device_tree/view/device_tree.html
- src/test/unit/web_interface/test_filter.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/filter.py
- added new filter for hiding large binary blobs inside device trees from the analysis view
- added view template for device tree plugin
- refactoring
> Device tree filter

- src/test/unit/test_manage_users.py
fixed an incompatibility with the new version of prompt-toolkit
> fix for incompatibility with new prompt-toolkit version

- src/web_interface/templates/upload/upload.html
Fixed a bug in the upload template where the POST request to `/upload` was not triggered on some systems
Resolves #750, resolves #757
> fix upload submit bug

- docsrc/index.rst
- docsrc/migration.rst
- docsrc/modules/helperFunctions.data_conversion.rst
- docsrc/modules/helperFunctions.object_conversion.rst
- docsrc/modules/helperFunctions.object_storage.rst
- docsrc/modules/helperFunctions.rst
- docsrc/modules/helperFunctions.virtual_file_path.rst
- src/fact_base.py
- src/start_fact.py
- src/start_fact_backend.py
- src/start_fact_db.py
- src/start_fact_frontend.py
- fail gracefully when:
- FACT is not installed
- FACT was upgraded to v4 but not reinstalled
- added docs for:
- migration from v3 to v4
- missing helper functions
> Graceful start fail

- README.md
- src/version.py
- src/web_interface/templates/about.html
- 3.3 release changes
- bumped version
- updated `readme.md`
- updated change log
> bumped version for release and updated readme + changelog

- src/plugins/analysis/kernel_config/code/kernel_config.py
- fixed an import error occurring in some cases during analysis with the `kernel_config` plugin
> kernel config plugin import bugfix

- src/plugins/analysis/kernel_config/code/kernel_config.py
- src/plugins/analysis/kernel_config/test/data/configs/old_config_build_file
- src/plugins/analysis/kernel_config/test/test_kernel_config.py
- added `has_kconfig_type()` function to check file type analysis for "kernel build file" type
- added support for old build config format
> improved kernel config detection

- docsrc/migration.rst
- src/config/migration.cfg
- src/config/mongod.conf
- src/migrate_db_to_postgresql.py
- added missing config files for MongoDB during migration
- improved docs
- improved migration user feedback
- pylint fixes
> Revised migration

- src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
- src/storage/db_interface_backend.py
- src/storage/db_interface_base.py
- fixed issue where the users_and_passwords plugin would still store byte strings in the result
- fixed error logging in case of DB JSON serialization errors (correct try-except case could not be reached)
> Users and pw bytes bugfix

- src/init_postgres.py
- src/install/requirements_backend.txt
- src/plugins/analysis/device_tree/requirements.txt
> Fix several bugs related to FACT_docker

- src/helperFunctions/object_conversion.py
- src/test/unit/helperFunctions/test_object_conversion.py
- src/test/unit/web_interface/rest/test_rest_file_object.py
changed `rest/file_object/<uid>` endpoint to return all virtual file paths instead of paths for one random Firmware
resolves #833
> changed rest/fo endpoint to return all VFPs

- src/objects/firmware.py
> Firmware: Remove dead code

- src/plugins/analysis/architecture_detection/internal/dt.py
- src/plugins/analysis/architecture_detection/internal/elf.py
- src/plugins/analysis/architecture_detection/view/cpu_architecture.html
- src/storage/db_interface_backend.py
- src/storage/entry_conversion.py
- src/test/unit/storage/test_entry_conversion.py
- [fix template compatibility with old results](https://github.com/fkie-cad/FACT_core/commit/e49e61ae68241af394eb4628213e402e8d2175f2)
- [fixed bug in arch detection plugin with empty arm sections](https://github.com/fkie-cad/FACT_core/commit/be12b8d7a8f38687be5070a9800e0454e1614fff)
- [fixed bug with null values in analysis result keys leading to DB errors](https://github.com/fkie-cad/FACT_core/commit/f92c7dde177f030c189df5d76607b0432489e34c)
- minor refactoring and typo fixes
should hopefully resolve #855  (I was unable to reproduce the error)
> Arch detection bugfixes

- src/install/requirements_common.txt
Bumped the version of LIEF to address recently discovered vulnerabilities in older versions.
> bumped lief version

- src/plugins/analysis/information_leaks/code/information_leaks.py
- src/plugins/analysis/information_leaks/test/test_plugin_information_leaks.py
I stumbled upon a .svn folder inside a D-Link firmware and had to discover that the "information_leaks" plugin did not detect it yet.
- added `.svn` artifacts to information leaks plugin
- updated some descriptions
- some minor refactoring
> added .svn artifacts to information leaks plugin

- src/fact_base.py
- src/start_fact.py
Added SIGTERM signal handler to support graceful shutdown of FACT running in a container (i.e. FACT_docker). This should solve the problems with the radare GUI in FACT_docker and resolve https://github.com/fkie-cad/FACT_docker/issues/32.
> added SIGTERM signal handler

- src/plugins/compare/file_coverage/code/file_coverage.py
- src/plugins/compare/file_coverage/test/test_plugin_file_coverage.py
- src/plugins/compare/file_coverage/view/file_coverage.html
- src/scheduler/comparison_scheduler.py
- src/storage/db_interface_admin.py
- src/storage/db_interface_comparison.py
- src/test/integration/storage/test_db_interface_comparison.py
- src/test/unit/compare/test_compare.py
- src/test/unit/scheduler/test_compare.py
> changed text files to file diff

- src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
- src/plugins/analysis/users_and_passwords/docker/Dockerfile
- src/plugins/analysis/users_and_passwords/docker/entry.sh
- src/plugins/analysis/users_and_passwords/test/data/passwd_test
- src/plugins/analysis/users_and_passwords/test/test_plugin_password_file_analyzer.py
- adjusted the Unix passwd regex so that passwords with empty salt are found
- extended the wordlist of john which was missing ssh and telnet default passwords
> adjusted PW regex for saltless unix PWs and extended john wordlist

- src/plugins/analysis/software_components/code/software_components.py
- src/plugins/analysis/software_components/signatures/database.yara
- src/plugins/analysis/software_components/signatures/lib.yara
- src/plugins/analysis/software_components/signatures/os.yara
- src/plugins/analysis/software_components/signatures/software.yara
- added no_text_file to software_components signatures where it was missing
- fixed errors in miniigd (wrong regex) and sqlite3 (wrong logic) signatures
resolves #404
> added no_text_file to software_components signatures where missing

- src/plugins/compare/file_coverage/view/file_coverage.html
- src/web_interface/static/js/file_tree.js
- src/web_interface/static/js/show_analysis_fileTreeAjax.js
- src/web_interface/templates/compare/compare.html
- src/web_interface/templates/show_analysis.html
applied the new file tree theme from the analysis page to the comparison page
> applied new file tree theme to comparison page

- src/plugins/analysis/string_evaluation/test/test_string_eval.py
- src/test/acceptance/base_full_start.py
- src/test/acceptance/test_compare_firmwares.py
- src/test/acceptance/test_io_routes.py
- src/test/acceptance/test_misc.py
- src/test/acceptance/test_upload_analyze_delete_firmware.py
- src/test/integration/intercom/test_task_communication.py
- src/test/unit/compare/test_compare.py
- src/test/unit/helperFunctions/test_plugin.py
- src/test/unit/helperFunctions/test_task_conversion.py
- src/test/unit/helperFunctions/test_uid.py
- src/test/unit/helperFunctions/test_yara_binary_search.py
- src/test/unit/scheduler/test_compare.py
- src/test/unit/scheduler/test_unpack.py
- src/test/unit/unpacker/test_unpacker.py
Preliminary work for my incoming rework of the tests.
> Replace asserts

- src/plugins/analysis/cve_lookup/code/cve_lookup.py
- src/scheduler/analysis.py
- src/test/unit/scheduler/test_analysis.py
- fixed a bug where a new version of packaging could lead to an uncaught exception in the cve_lookup plugin
- also fixes a test
> cve_lookup: bugfix for InvalidVersion in new packaging version

- src/analysis/PluginBase.py
- src/config.py
- src/config/main.cfg
- src/conftest.py
- src/scheduler/analysis.py
- src/test/data/load_cfg_test
- src/test/data/load_cfg_test_missing_entrys
> added analysis plugin threads default value

- src/helperFunctions/process.py
2efbf0b4 accidently changed the docstring.
> src/helperFunctions/process: Fix docstring

- src/flask_app_wrapper.py
- src/helperFunctions/merge_generators.py
- src/storage/db_interface_common.py
- src/test/integration/storage/test_db_interface_common.py
Resolves #944 
I used vulture a couple of times in the past already. This time there was not that much unused code but still worth a PR IMO
> removed some unused functions

- src/plugins/analysis/ipc/code/ipc_analyzer.py
- src/plugins/analysis/ipc/test/test_ipc_analyzer.py
- bugfix for empty results in ipc plugin summary
- changed summary to use result entry types as items
> ipc plugin summary bugfix

- src/analysis/PluginBase.py
- src/fact_base.py
- src/helperFunctions/process.py
- src/intercom/back_end_binding.py
- src/plugins/analysis/qemu_exec/code/qemu_exec.py
- src/scheduler/analysis.py
- src/scheduler/analysis_status.py
- src/scheduler/unpacking_scheduler.py
- src/start_fact_backend.py
- src/storage/unpacking_locks.py
- src/test/acceptance/base.py
- src/test/acceptance/test_authenticated_gui.py
- src/test/integration/scheduler/test_cycle_with_tags.py
- src/test/integration/scheduler/test_regression_virtual_file_path.py
- src/test/integration/scheduler/test_unpack_and_analyse.py
- src/test/integration/scheduler/test_unpack_only.py
- src/test/unit/scheduler/test_analysis.py
- src/test/unit/scheduler/test_analysis_status.py
- src/test/unit/unpacker/test_unpacker.py
- replaced killing of the whole process group with only stopping remaining subprocesses
- handled shutdown of `multiprocessing.Manager` correctly
- only log reception of shutdown signal in main process (to reduce logging spam during shutdown)
> Optimized shutdown

- src/web_interface/components/analysis_routes.py
#962 fixed this for the upload page but not for the update/redo page.
> update page plugin preset bugfix

- src/analysis/PluginBase.py
- src/intercom/back_end_binding.py
- src/plugins/analysis/cwe_checker/code/cwe_checker.py
- src/scheduler/analysis.py
- src/scheduler/analysis_status.py
- src/scheduler/comparison_scheduler.py
- src/scheduler/unpacking_scheduler.py
- src/storage/binary_service.py
- src/storage/unpacking_locks.py
- src/test/unit/scheduler/test_compare.py
* fixed shutdown of new analysis stats manager processes
* removed unnecessary logging of cwe_checker and binary service
* added PIDs to some logging messages for debugging
* added back comparison admin db interface (that was removed in [2efbf0b4d0e232d30af716246388c41e4a166930](https://github.com/fkie-cad/FACT_core/commit/2efbf0b4d0e232d30af716246388c41e4a166930) for unknown reasons?)
* fixed the restart of the comparison worker
> Backend logging fix

- src/analysis/PluginBase.py
- src/conftest.py
- src/intercom/back_end_binding.py
- src/scheduler/analysis.py
- src/scheduler/comparison_scheduler.py
- src/scheduler/unpacking_scheduler.py
- src/start_fact_backend.py
- src/test/acceptance/base.py
- src/test/acceptance/test_authenticated_gui.py
- src/test/integration/intercom/test_backend_scheduler.py
- src/test/integration/scheduler/test_cycle_with_tags.py
- src/test/integration/scheduler/test_regression_virtual_file_path.py
- src/test/integration/scheduler/test_unpack_analyse_and_compare.py
- src/test/integration/scheduler/test_unpack_and_analyse.py
- src/test/integration/scheduler/test_unpack_only.py
- src/test/integration/web_interface/rest/test_rest_binary.py
- src/test/unit/analysis/test_plugin_base.py
- src/test/unit/scheduler/test_analysis.py
- src/test/unit/scheduler/test_unpack.py
This is needed for upcoming #895
> Dont start processes in init

- src/config.py
- src/config/main.cfg
- src/conftest.py
- src/storage/redis_interface.py
- src/test/data/load_cfg_test
- src/test/data/load_cfg_test_missing_entrys
> added optional authentication for Redis

- src/install/backend.py
because output of v4.3 has changed which causes a parsing error
ToDo: upgrade YARA to 4.3 and fix parsing errors
> pinned YARA version to 4.2.3

- src/storage/query_conversion.py
- src/test/integration/storage/test_db_interface_frontend.py
- src/web_interface/templates/database/database_advanced_search.html
- [added unequal operator for advanced search](https://github.com/fkie-cad/FACT_core/commit/af539764cd354a70494f89b35528620e2d87f885)
- [added more examples to advanced search template](https://github.com/fkie-cad/FACT_core/commit/94f551aded777c96d1ca7b454d77ed3d9da4468a)
> Unequal advanced search

- src/web_interface/static/js/advanced_search.js
- src/web_interface/templates/database/database_advanced_search.html
- replaced advanced search input with text area 
- because the input was too small for complex queries
- added query input validation
- the validation only checks for valid JSON at the moment
- but it fixes trailing commas
- validation before posting has the advantage that you don't lose the query that you were typing
- also removed old unused angular code
> replaced advanced search input with text area and added validation

- src/storage/entry_conversion.py
- src/test/unit/storage/test_entry_conversion.py
- Fixes a bug where files with illegal names could not be added to database, as vfp still contains illegal symbols (file name is already sanitized)
> Added unicode error handling in data sanitization

- src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
- src/plugins/analysis/users_and_passwords/docker/Dockerfile
The use of a better wordlist should significantly improve the password cracking abilities of the "users & passwords" plugin (while increasing the average runtime a bit)
> users & passwords: use better wordlist

- src/plugins/analysis/cwe_checker/code/cwe_checker.py
- application/x-pie-executable previously omitted due to negligence
> Added pie mime type to cwe_checker whitelist

- src/unpacker/unpack.py
Somehow, we seem to never reach this code anyway (that's probably why we never noticed this bug)
> unpacking fs_organizer bugfix

- src/web_interface/static/package-lock.json
- src/web_interface/static/package.json
- src/web_interface/templates/show_analysis.html
why did nobody notice that the syntax highlighting is broken?
> preview syntax highlighting fix

- src/test/unit/web_interface/test_app_static.py
- src/web_interface/templates/compare/text_files.html
* [added test that verfies static urls from templates are found](https://github.com/fkie-cad/FACT_core/commit/aff1a0895f2b8d99e1e3dae01a990a0b8378f847)
* [fixed highlight.js link in text file comparison template](https://github.com/fkie-cad/FACT_core/commit/d6f62dd22a46510c3690c09e59fcc92f0baaafa4)
> Static file path resolution test

- INSTALL.md
- fixed TL;DR
- updated sections
- added venv section
- revised formatting
- it was not possible to copy the code blocks directly because of the preceding "$"
> revised install.md

- .pre-commit-config.yaml
- pyproject.toml
- src/init_postgres.py
cherrypicked the configuration fixes/updates from #1045
> Ruff update config

- src/config/fact-core-config.toml
Must have slipped through the review of #976
> config: Remove duplicate entry

- src/fact_base.py
- src/start_fact_backend.py
- added log messages for RAM usage
- refactored `fact_base` to avoid code duplication
> added log messages for RAM usage

- src/install/frontend.py
- src/install/pre_install.sh
- src/install/requirements_frontend.txt
- src/plugins/analysis/architecture_detection/requirements.txt
- src/start_fact_frontend.py
supersedes #1085 (if it works)
> Update pre install

- src/helperFunctions/install.py
* [added Linux Mint 21.2 codename](https://github.com/fkie-cad/FACT_core/commit/374451214b458c33efd900e49a6d2ebaef3da7f9)
* [updated warning message, refactoring, typo and ruff fixes](https://github.com/fkie-cad/FACT_core/commit/43e8f75b28885c7d5c3de7d56706765e31faa118)
> Distro check update

- src/conftest.py
- src/helperFunctions/database.py
- src/test/acceptance/conftest.py
- src/test/acceptance/test_upload_analyze_delete_firmware.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/components/analysis_routes.py
- src/web_interface/components/compare_routes.py
- src/web_interface/components/component_base.py
- src/web_interface/components/database_routes.py
- src/web_interface/components/io_routes.py
- src/web_interface/components/miscellaneous_routes.py
- src/web_interface/components/statistic_routes.py
- src/web_interface/frontend_main.py
- src/web_interface/rest/rest_binary.py
- src/web_interface/rest/rest_binary_search.py
- src/web_interface/rest/rest_compare.py
- src/web_interface/rest/rest_firmware.py
- src/web_interface/rest/rest_resource_base.py
- src/web_interface/rest/rest_status.py
* removed ConnectTo class (which was used to connect to the intercom but has been obsolete for a while)
* refactoring and some typo and ruff fixes
> Remove connect to

- src/scheduler/analysis/scheduler.py
> fixed bug that may occur when a dependency result is missing

- src/test/integration/web_interface/rest/test_rest_analysis.py
- src/test/unit/web_interface/rest/test_rest_analysis.py
- src/web_interface/rest/rest_analysis.py
- src/web_interface/rest/rest_base.py
added `/rest/analysis/<uid>/<plugin>` REST endpoint for requesting the result of a specific analysis plugin of a specific file
> added /rest/analysis endpoint

- src/analysis/plugin/plugin.py
- src/scheduler/analysis/plugin.py
- src/storage/db_interface_backend.py
- src/storage/schema.py
> AnalysisPluginV0 fixes

- src/plugins/analysis/example_plugin/code/example_plugin.py
Now when creating the json schema it also includes the description.
> plugin/ExamplePlugin: Use pydantic descriptions

- src/plugins/analysis/file_system_metadata/code/file_system_metadata.py
- src/plugins/analysis/file_system_metadata/test/test_plugin_file_system_metadata.py
* restructured plugin "file_system_metadata"
* instead of a class instance variable `result` let the functions return stuff
* some more refactoring and test fixes
> fs_metadata plugin: restructure code + refactoring

- src/helperFunctions/docker.py
- docker helper function: handle/log other requests connection exceptions (see #1154)
> helper docker: handle/log more connection errors

- src/fact_base.py
- src/plugins/analysis/device_tree/code/device_tree.py
- src/plugins/analysis/device_tree/internal/schema.py
- src/plugins/analysis/device_tree/test/test_device_tree.py
An oversight in rebasing https://github.com/fkie-cad/FACT_core/pull/1028
> chore: Run fix ruff errors

- .gitignore
Small fix to get `git` to stop complaining.
> Replace start_fact_db with start_fact_database in .gitignore

- src/plugins/analysis/crypto_hints/code/crypto_hints.py
- src/storage/migration/versions/05d8effce8b3_add_gin_index_to_analysis_result.py
- src/storage/schema.py
- added GIN index to speed up certain queries on the JSONB results column of table analysis
- added alembic migration script
> db schema: added result GIN index + migration

- src/plugins/analysis/crypto_hints/code/crypto_hints.py
- src/plugins/analysis/crypto_hints/view/crypto_hints.html
- src/test/unit/web_interface/test_filter.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/filter.py
- [crypto hints: added hex value to template](https://github.com/fkie-cad/FACT_core/commit/d40d27297443c20c0505a89a00b27f7e67aeab92)
- [filter: added str2hex filter](https://github.com/fkie-cad/FACT_core/commit/ad1f675ea231dc6cfbc165bd56c5cb1b3404ec19)
> Crypto hints hex

- src/web_interface/components/hex_highlighting.py
- fixes a bug in the hex file preview where the preview text was not properly escaped
> hex preview: proper html escape bug fix

- src/plugins/analysis/example_plugin/code/example_plugin.py
Formatting commends only work at statement level [1]. [1]: https://docs.astral.sh/ruff/formatter/#format-suppression
> chore: Fix formatting

- src/test/acceptance/test_advanced_search.py
- src/test/common_helper.py
- src/test/unit/web_interface/test_app_advanced_search.py
- src/web_interface/components/database_routes.py
- this feature confused people more than it helped
- fixed tests
> removed redirect in case of a single search result

- src/plugins/analysis/software_components/view/software_components.html
- src/web_interface/static/js/show_analysis_preview.js
- src/web_interface/templates/analysis_plugins/general_information.html
- src/web_interface/templates/show_analysis.html
- [added option to view raw analysis result](https://github.com/fkie-cad/FACT_core/commit/ed4153d681b7f2b5105eddc699f44ac2efd94fb1)
- [removed hack from software components template](https://github.com/fkie-cad/FACT_core/commit/a1f93d9a42c52eb78bd22dca66dd726de626a9e6) (so that is works together with the raw analysis view)
> Show raw analysis

- src/plugins/analysis/file_system_metadata/code/file_system_metadata.py
- src/plugins/analysis/file_system_metadata/test/test_plugin_file_system_metadata.py
- src/scheduler/analysis/plugin.py
- added support for YAFFS filesystems to the filesystem metadata plugin
> Fs metadata yaffs

- src/plugins/analysis/file_system_metadata/code/file_system_metadata.py
- src/plugins/analysis/file_system_metadata/routes/ajax_view.html
- src/plugins/analysis/file_system_metadata/test/test_file_system_metadata_routes.py
- src/plugins/analysis/file_system_metadata/test/test_plugin_file_system_metadata.py
- src/plugins/analysis/file_system_metadata/view/file_system_metadata.html
- src/test/unit/web_interface/test_filter.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/filter.py
- also show file type if the file mode data includes this
- change the label in the result from "permissions" to "file mode"
> fs metadata: show mode incl. type

- src/statistic/update.py
- fixes the following bug: if `get_general_stats()` is called after `update_all_stats()`, the "generation time" will be wrong until FACT is restarted
> stats generation time bug fix

- .gitignore
- README.md
- src/firmware_import_export.py
- src/helperFunctions/virtual_file_path.py
- src/objects/file.py
- src/objects/firmware.py
- src/storage/migration/__init__.py
- src/test/integration/run_scripts/test_import_export.py
- src/test/unit/helperFunctions/test_virtual_file_path.py
- feat: added CLI script for importing/exporting FW (including unpacked files and analysis results)
resolves #1250, resolves #446
> FW import/export

- src/scheduler/analysis/scheduler.py
and also fixed some typos, added missing commas and improved the wording (to make them easier to understand)
> docs: fixed outdated scheduler docstrings

- src/helperFunctions/magic.py
- src/install/common.py
- fixes warnings like 'Warning: using regular magic file ...'
- bump FW magic version to v0.2.2
> Fix file magic warnings

- src/plugins/analysis/input_vectors/code/input_vectors.py
- src/plugins/analysis/known_vulnerabilities/code/known_vulnerabilities.py
- src/plugins/analysis/known_vulnerabilities/test/test_known_vulnerabilities.py
- src/plugins/analysis/software_components/code/software_components.py
- src/plugins/analysis/software_components/internal/resolve_version_format_string.py
- src/plugins/analysis/software_components/test/test_resolve_version_format_string.py
mount the file directly into the container instead of writing the contents into another file and mounting that file
- known_vulnerabilities
- input_vectors
- software_components (FSR)
> analysis plugins: improved docker mount efficiency

- src/test/integration/web_interface/rest/test_rest_firmware.py
- src/test/unit/web_interface/rest/test_rest_firmware.py
- src/web_interface/rest/rest_firmware.py
> added rest delete FW endpoint

- .gitignore
- .pre-commit-config.yaml
On new installations paths to the local cve database and node modules / nodeenv has changed
> Updated .gitignore

- src/web_interface/static/css/base.css
* fixed altert-primare element that is displayed when starting a binary search
* multiple small fixes for the text file diff
> fix: even more dark mode fixes

- src/web_interface/components/statistic_routes.py
- src/web_interface/static/css/base.css
- src/web_interface/static/js/system_health.js
- src/web_interface/templates/base.html
- src/web_interface/templates/generic_view/nice_fo_list.html
- src/web_interface/templates/plugins.html
- src/web_interface/templates/system_health.html
- [moved queues into own table](https://github.com/fkie-cad/FACT_core/pull/1338/commits/8c42c5a8e706470d29d879a2027af1440e85ecf1)
- [moved plugin cards from system health to their own page](https://github.com/fkie-cad/FACT_core/pull/1338/commits/0f4c118f8db903525041beca0acef88b0113f536)
- [fix for nice list border bug](https://github.com/fkie-cad/FACT_core/pull/1338/commits/4da0997c27702d4860cb56d85e9f2f8250cd3705)
> System health stage3

- src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
- src/plugins/analysis/users_and_passwords/docker/Dockerfile
- src/plugins/analysis/users_and_passwords/internal/credentials_finder.py
- src/plugins/analysis/users_and_passwords/test/test_plugin_password_file_analyzer.py
- added more pw cracking word lists
- updated unix passwd regexes to...
- reduce FPs (especially IPv6 addresses)
- add support for yescrypt
> feat: extended pw cracking wordlist of users&pw plugin

- src/plugins/analysis/known_vulnerabilities/code/known_vulnerabilities.py
- src/plugins/analysis/known_vulnerabilities/internal/rulebook.py
- src/plugins/analysis/known_vulnerabilities/test/test_known_vulnerabilities.py
- src/plugins/analysis/known_vulnerabilities/test/test_rulebook.py
- src/plugins/analysis/known_vulnerabilities/view/known_vulnerabilities.html
> feat: converted known_vulnerabilities plugin to new base class
