fkie-cad/FACT_core

- src/helperFunctions/rest.py
- src/storage/db_interface_frontend.py
- src/test/acceptance/test_advanced_search.py
- src/test/common_helper.py
- src/test/unit/web_interface/rest/test_rest_firmware.py
- src/web_interface/rest/rest_firmware.py
Implementation using the existing generic_search function.
Recursive search is not allowed for empty queries to prevent querying the complete database.
> Rest firmware supports recursive search

- src/intercom/back_end_binding.py
- src/intercom/common_mongo_binding.py
- src/intercom/front_end_binding.py
- src/scheduler/Analysis.py
- src/test/acceptance/rest/test_rest_analyze_firmware.py
- src/test/acceptance/rest/test_rest_download.py
- src/test/common_helper.py
- src/test/integration/intercom/test_backend_scheduler.py
- src/test/unit/web_interface/rest/test_rest_firmware.py
- src/web_interface/rest/rest_firmware.py
Allows adding or updating an analysis to a firmware without running mandatory plugins or unpacker.
Feature is implemented as REST-only at the moment.
Implementation:
- added intercom listener to differentiate between updating w/, w/o unpacker
- REST endpoint checks if unpacker is requested, triggers intercom accordingly
> Update analysis without unpacking

- src/helperFunctions/rest.py
- src/test/integration/web_interface/rest/test_rest_firmware.py
- src/test/unit/helperFunctions/test_rest.py
- src/test/unit/web_interface/rest/test_rest_firmware.py
- src/web_interface/rest/rest_firmware.py
When adding `?summary=true` to a firmware request, the summaries are collected from all child objects.
> Add parameter and lots of tests

- src/storage/binary_service.py
- src/test/unit/unpacker/test_tar_repack.py
- src/unpacker/tar_repack.py
- src/unpacker/unpackBase.py
There were some problems with downloading tar.gz archives.
This stemmed from files being extracted as root-owned or missing write permissions.
The problem is fixed via an already existing function in the `unpackBase`.
Code was refactored though.
> fixed issue with bad directory cleanup

- src/bootstrap/bootstrap_frontend.sh
- src/web_interface/templates/about.html
- src/web_interface/templates/show_analysis.html
Solves SD-54 Syntax Highlighting.
Supported languages are the "Common" options of
https://highlightjs.org/download/
If more languages should be supported, the download script may be adjusted.
At the moment, a pre-built package is downloaded faking a post request requiring a cookie.
The other option would be to download the github sources and build the package. That would require node and npm to be installed on the users system.
> code preview hightlighting added

- src/intercom/back_end_binding.py
- src/scheduler/Unpacking.py
- src/storage/db_interface_backend.py
- src/storage/db_interface_common.py
- src/test/common_helper.py
- src/test/integration/common.py
- src/test/integration/intercom/test_intercom_delete_file.py
- src/test/integration/scheduler/test_unpack_and_analyse.py
- src/test/integration/scheduler/test_unpack_only.py
- src/test/integration/storage/test_db_interface.py
- src/test/unit/scheduler/test_unpack.py
- src/test/unit/unpacker/test_unpacker.py
- src/unpacker/unpack.py
Problem of race condition has appeared since binary deletion was activated recently.
Whenever a firmware is deleted, issuing a cascade of file deletions, a new analysis can overlap with the files. Then a file can be extracted during analysis, deleted shortly after due to the firmware deletion, and analyzed later on at which point the file has been deleted.
This happens basically every time a re-do anlysis is issued, but can happen in other scenarios as well.
A locking of extracted files should prevent that from happening. That is:
1. Unpacker finds file
2. file is locked
3. file is stored on fs
4. file is analyzed
5. analysis is stored in database
6. lock is released
As of now, if a deletion request is issued in between steps 3 and 5, the file is remove as no database link exists to it. …
> Locking unpacked files

- src/helperFunctions/mongo_task_conversion.py
- src/test/acceptance/rest/test_rest_compare.py
- src/test/acceptance/test_compare_firmwares.py
- src/test/acceptance/test_misc.py
- src/test/acceptance/test_upload_analyze_delete_firmware.py
- src/test/common_helper.py
- src/test/integration/web_interface/rest/test_rest_firmware.py
- src/test/unit/helperFunctions/test_mongo_task_conversion.py
- src/test/unit/web_interface/rest/test_rest_firmware.py
- src/test/unit/web_interface/test_app_re_analyze.py
- src/test/unit/web_interface/test_app_upload.py
- src/web_interface/rest/rest_firmware.py
- src/web_interface/templates/upload/re-analyze.html
- src/web_interface/templates/upload/upload.html
Fixing mismatched naming of firmware version, where in database and object `version` was used and upload used `firmware_version`.
Side effect: Removed unused function `convert_fw_obj_to_analysis_task` from task conversion helper.
Name was already changed in wiki.
> Align version naming

- pytest.ini
cwe_checker internal tests require precompiled binaries to run. FACT should not deal with internal cwe_checker tests.
> Fixed discovery problem of pytest with cwe_checker

- pytest.ini
Note that I have added the option to the CI scripts. Only difference is in use on CL where you now have to add it manually.
Upside is, that debugger like in PyCharm, using same hooking library as coverage can now work without user having to first change pytest.ini.
> Removed from config so that IDE toolchains work correctly

- src/install/backend.py
Hello,
I have tried installing FACT on a clean ubuntu 18.04 VM. I encountered the following error:
```
checking arpa/inet.h presence... yes
configure: WARNING: arpa/inet.h: present but cannot be compiled
configure: WARNING: arpa/inet.h:     check for missing prerequisite headers?
configure: WARNING: arpa/inet.h: see the Autoconf documentation
configure: WARNING: arpa/inet.h:     section "Present But Cannot Be Compiled"
configure: WARNING: arpa/inet.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------------------------- ##
configure: WARNING:     ## Report this to http://firmware-mod-kit.googlecode.com ##
configure: WARNING:     ## ----------------------------------------------------- ##
checking for arpa/inet.h... no
```
Running `autoconf` …
> backend install: run autoconf (fixes install on ubuntu 18.04)

- src/install/backend.py
The fix in PR #208 does not seem to work reliably (see ![CI build](https://ci.die-weidenbachs.de/job/FACT_core_bionic/374/console)).
Thus to smooth out builds, temporarily checkout 'mod-kit from before latest commit
> temporary fix. downgrade modkit from latest commit

- src/web_interface/templates/generic_view/firmware_detail_tabular_field.html
- src/web_interface/templates/home.html
- src/web_interface/templates/show_analysis.html
addresses #256
- most links in the web interface were not compatible with the "open as new tab" context menu entry
- fixed dead links on timestamps for latest analyses
> made most links tab compatible + fixed dead link

- src/test/unit/scheduler/test_analysis_tag.py
test_start_process from /test/unit/scheduler/test_analysis_tag.py failed randomly 
probably because the new ci is slower and the sleep/wait time needs to be adjusted
> changed delay in test

- src/helperFunctions/program_setup.py
- src/plugins/compare/file_coverage/view/file_coverage.html
- src/start_fact.py
- src/start_fact_backend.py
- src/start_fact_db.py
- src/start_fact_frontend.py
- removed SIGTERM signal handlers (unnecessary)
- in case FACT was started using the start_fact script:
- remove SIGINT signal handler and use handler for SIGUSER1 to propagate the shutdown
- reset PGID in the start_backend script so that `complete_shutdown` doesn't kill the other scripts
> 264 fix shutting down fact bug

- src/plugins/analysis/cwe_checker/code/cwe_checker.py
- src/plugins/analysis/cwe_checker/install.sh
- src/plugins/analysis/cwe_checker/test/test_cwe_checker.py
Since cwe_checker changed its output format, we have to parse json instead of sexp. Good news: this makes the FACT plugin much smaller! :+1: 
Please do not merge before PR #32 of cwe_checker has been merged (https://github.com/fkie-cad/cwe_checker/pull/32).
> Fix broken cwe_checker plugin

- src/plugins/analysis/input_vectors/install.sh
Got the following error:
```python
ERROR    root:input_vectors.py:51 Could not decode JSON output.
ERROR    root:input_vectors.py:52 Traceback (most recent call last):
File "/home/r2/input_vectors/input_vectors_r2.py", line 8, in <module>
import r2pipe
ModuleNotFoundError: No module named 'r2pipe'
```
Turned out that the input vector plugin build a docker container on an old base version of fkiecad/radare-web-gui.
> pull latest docker container before build to avoid dependency issues

- src/compile_yara_signatures.py
- src/install.py
- src/install/pre_install.sh
- src/start_fact_backend.py
- src/start_fact_db.py
- src/update_statistic.py
- src/update_variety_data.py
- src/version.py
- src/web_interface/templates/about.html
The FACT installation may break on systems having the [enum34](https://pypi.org/project/enum34/) package installed.
```
AttributeError: module 'enum' has no attribute 'IntFlag'
```
Since python 3.4 there's a standard library `enum` module, so we should uninstall enum34,
which is no longer compatible with the `enum` in the standard library since `enum.IntFlag` was added in [python 3.6](https://docs.python.org/3/library/enum.html).
```
pip3 uninstall -y enum34
```
However, automatic uninstalling may cause unexpected side effects for the affected users still using the package. As a result, this PR modifies the `pre_install.sh` script to exit preemptively if the package is found
> Added check for enum34, update copyright strings

- src/helperFunctions/web_interface.py
- src/install/frontend.py
- src/storage/db_interface_frontend.py
- src/test/integration/storage/test_db_interface_frontend.py
- src/test/unit/helperFunctions/test_web_interface.py
- src/test/unit/web_interface/base.py
- src/test/unit/web_interface/test_app_missing_analyses.py
- src/web_interface/components/miscellaneous_routes.py
- src/web_interface/templates/base.html
- src/web_interface/templates/find_missing_analyses.html
addresses #344
added new page `/admin/missing_analyses` that shows:
- missing files (files that are included in another file_object/firmware but are not found in the DB)
- missing analyses (analyses that are present in the firmware object but not in included file_objects)
> Experimental find failed analyses

- src/helperFunctions/mongo_task_conversion.py
Fixed XSS but by adding the flask escape function to escape user's input when updating details of the firmware. Related to issue #375
> Fix XSS bug by escaping user input when updating firmware details

- src/storage/db_interface_frontend.py
- src/test/acceptance/test_advanced_search.py
- src/test/common_helper.py
- src/web_interface/components/database_routes.py
- src/web_interface/templates/database/database_advanced_search.html
- src/web_interface/templates/database/database_browse.html
- added "inverse" option to advanced search (only firmware)
- this enables previously impossible search queries (e.g. firmware without busybox)
> Sd 979 inverse advanced fw search

- src/plugins/analysis/elf_analysis/code/elf_analysis.py
- src/storage/MongoMgr.py
- flake8 found `connect=False` out of scope and does not like `l` named variables anymore
- some pylint errors fixed along the way. Thanks pre-commit
> fixed flake8 indication including a real bug

- src/web_interface/components/ajax_routes.py
- src/web_interface/templates/about.html
- src/web_interface/templates/show_analysis.html
fixed a bug where the links in the file tree were incorrect for file objects on the analysis page without root UID
> fixed a file tree bug regarding missing root uids

- src/config/main.cfg
- src/helperFunctions/config.py
- src/helperFunctions/mongo_task_conversion.py
- src/plugins/analysis/binwalk/code/binwalk.py
- src/plugins/analysis/file_system_metadata/code/file_system_metadata.py
- src/plugins/analysis/input_vectors/code/input_vectors.py
- src/plugins/analysis/qemu_exec/code/qemu_exec.py
- src/plugins/analysis/software_components/code/software_components.py
- src/plugins/analysis/software_components/internal/resolve_version_format_string.py
- src/test/unit/helperFunctions/test_config.py
- src/test/unit/helperFunctions/test_mongo_task_conversion.py
- src/unpacker/tar_repack.py
- src/unpacker/unpack.py
- src/web_interface/components/database_routes.py
- src/web_interface/components/io_routes.py
The path for Temporary Directories is now configurable in the configuration file (`main.cfg`). This can be useful when the user running FACT doesn't have full access to `/tmp`
> made temp dir path configurable

- src/storage/db_interface_compare.py
We noticed a bug where comparisons were not being added to the
database properly due to the 'entropy' key not being present in
the 'unpacker' dict, so we added some handling so that we could
process comparisons correctly.
> Fixing bug that prevented comparisons

- src/config/main.cfg
- src/helperFunctions/web_interface.py
- src/test/common_helper.py
This PR makes the radare2 host url configurable via the main.cfg
file. The default value is set to 'localhost', but should be set
to the IP or hostname of where ever the radare service is running
in distributed configurations.
Fixes #436
> Making radare web service host/ip configurable

- src/plugins/analysis/elf_analysis/code/elf_analysis.py
- src/plugins/analysis/elf_analysis/test/test_plugin_elf_analysis.py
- src/plugins/analysis/elf_analysis/view/elf_analysis.html
fixes #442
-  values of "virtual_address" and "offset" for sections and segments are converted to hex strings (to fix problems with 8-bit integers and MongoDB)
- fixed collapsing elements in template so that they only collapse when the header is clicked and not the whole table (so that a user can actually select and copy results)
> Sd1167 fix 8bit mongo issues

- src/web_interface/templates/generic_view/file_object_macros.html
The download link template was broken and did not allow
for a user to download the appropriate file.  This commit
fixes the issue
> Bugfix for download link template

- src/plugins/analysis/cwe_checker/code/cwe_checker.py
Adjusting the global plugin timeout to give the plugin enough time to gracefully shut down if the cwe_checker itself runs into a timeout.
> adjust global timeout

- src/storage/db_interface_admin.py
- src/storage/db_interface_common.py
- src/test/integration/storage/test_db_interface.py
- duplicate entries in the "sanitize_db" were created each time `sanitize_analysis()` was called
- fix: only create entry if there is none or if it has changed and delete old ones
> no more sanitize db duplicate entries

- src/storage/db_interface_frontend.py
- src/test/common_helper.py
- src/test/integration/storage/test_db_interface_frontend.py
- src/test/integration/web_interface/rest/test_rest_missing_analyses.py
- src/test/unit/web_interface/test_app_missing_analyses.py
- src/web_interface/components/miscellaneous_routes.py
- src/web_interface/rest/rest_missing_analyses.py
- src/web_interface/templates/find_missing_analyses.html
- added "orphaned objects" to the missing analyses page, showing file objects whose parent firmware is missing from the database
> Orphaned objects

- src/plugins/analysis/cwe_checker/install.sh
Switch to the stable cwe_checker Docker image, since the latest container will introduce some breaking changes to its interface in the the future.
> Switch to stable cwe_checker-Docker-image

- src/web_interface/components/ajax_routes.py
this should fix a bug with the live stats on the "home" page when no stats can be retrieved from the DB (see #538)
> fixed bug in live stats

- src/compare/compare.py
- src/objects/file.py
- src/test/unit/objects/test_file.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/templates/generic_view/general_information.html
- src/web_interface/templates/show_analysis.html
- fixed a bug where the wrong virtual file paths were displayed on the analysis page
- changed the shown virtual paths in case no "root uid" is provided from a random firmware container to all firmware containers
> Sd1446 vfp wrong rootfw bugfix

- src/install/pre_install.sh
I didn't have `lsb-release` installed and then wondered why I got `E: Malformed entry 50 in list file /etc/apt/sources.list` later. Now the `pre_install.sh` will print an error when CODENAME is empty.
> pre_install.sh: Check if CODENAME is nonempty

- src/install/frontend.py
- pinned version of `sqlalchemy` because of errors in combination with `flask_sqlalchemy`
> bugfix: pinned sqlalchemy

- src/plugins/analysis/cve_lookup/internal/data_parsing.py
- src/plugins/analysis/cve_lookup/internal/database_interface.py
- src/plugins/analysis/cve_lookup/internal/setup_repository.py
- src/plugins/analysis/cve_lookup/test/test_database_interface.py
- src/plugins/analysis/cve_lookup/test/test_setup_repository.py
resolves #568 
there were some problems with the setup of the cve_lookup plugin:
- CVE entries can have CPE names with colons (which breaks parsing)
- there are new (broken?) CPE entries without "cpe23Uri"
- improved (more informative) error logging
> fixed bug in cve_lookup setup + improved error logging

- src/plugins/analysis/qemu_exec/code/qemu_exec.py
- src/plugins/analysis/qemu_exec/install.sh
Previously `pgrep dockerd` was used to detect whether docker is running.
This assumes that the process is called "dockerd" and also is part of the
current the pid_namespace.
`docker info` on the other hand relies on docker's internal logic to find
out whether the server is running or not.
References #561
> analysis/qemu_exec: Use `docker info` to test if docker is running

- src/install/frontend.py
resolves #576 
- pin `flask` and `itsdangerous` because of incompatibilities with `flask_restful` and `flask_security`
> 576 flask version bugfix

- src/helperFunctions/plugin.py
remove redundant warnings like
```
[2021-06-18 11:56:20][plugin][WARNING]: Plugin has no code directory: /home/user/git/FACT_core/src/plugins/analysis/__pycache__
```
> fix unnecessary warnings in plugin system

- src/start_fact_frontend.py
Fixed a bug where the SIGINT signal was not forwarded to uWSGI when starting FACT with `start_fact.py` / `start_all_installed_fact_components`
> frontend signal forwarding bugfix

- src/scheduler/Analysis.py
- src/test/unit/scheduler/test_analysis.py
- src/web_interface/components/analysis_routes.py
- src/web_interface/templates/about.html
- src/web_interface/templates/show_analysis.html
Added option to force re-analysis (aka "skip skip") for single file analysis.
Will directly be marked as deprecated and removed as soon as the following features are implemented:
> added checkbox to force single analysis update

- src/helperFunctions/mongo_task_conversion.py
- fixed deprecation warning of escape function:
> 'jinja2.escape' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.escape' instead.
- fixed possible miss of TemporaryDirectory cleanup function
- slight refactoring with pathlib
> escape deprecation fix + tmp file cleanup miss fix

- src/web_interface/templates/base.html
fixed navbar scaling for screen widths around half of FHD or QHD (which was broken since the admin dropdown menu was always displayed)
- removed FACT title from navbar
- reduced size of quick search input
- made this input grow bigger when being focused on 
- made navbar collapsible for very small screens
- when authentication is turned on, long user names could still be problematic (because of the additional menu entry)
> fixed navbar scaling for medium width

- src/helperFunctions/mongo_task_conversion.py
- src/scheduler/Analysis.py
- src/web_interface/components/analysis_routes.py
- src/web_interface/static/js/system_health.js
- src/web_interface/templates/about.html
- src/web_interface/templates/system_health.html
- changed "update analysis" so that unpacking is skipped
- added entry to `about.html`
- fixed "current analysis progress" in "system health" so that progress is displayed correctly for updates
- fixed a bug where certain combinations of unpacking and analysis progress in combination with minimum length of the progress text were causing the progress bar lengths to be displayed wrongly
- refactoring (f-string + pylint fixes)
> update without unpacking

- src/web_interface/templates/show_analysis.html
Resolves #649 
- fixes library and stylesheet paths
- replaces deprecated function
> fixed incompatibility with newest highlight.js version

- .pre-commit-config.yaml
Maybe it is just me but out of habit I sometimes still use double quotes instead of single quotes.
This enforces single quotes.
> pre-commit: Add double-quote-string-fixer

- src/install/frontend.py
- src/plugins/analysis/linter/code/source_code_analysis.py
- src/plugins/analysis/linter/install.sh
- src/plugins/analysis/linter/test/test_js_linter.py
- src/test/acceptance/test_io_routes.py
- src/web_interface/templates/dependency_graph.html
- replaced flaky npm link for vis-network with unpkg link
- updated version to 8.5.6 (9.x.x was really laggy for no apparent reason)
- updated template
- made legend non-interactable and a bit thinner
- added border to visualize where graph ends (so that it doesn't look broken)
- skipped jshint installation and respective tests and removed javascript from linter plugin (this should be reverted when the eslint branch is merged)
- ~~skipped radare test (seems to be broken for the CI as it is now)~~ (rh: we managed to locate the infrastructural issue and reactivated the test)
> added new source for vis-network + updated template

- .pre-commit-config.yaml
- src/helperFunctions/hash.py
- src/helperFunctions/install.py
- src/install/backend.py
- src/install/common.py
- src/plugins/analysis/hash/code/hash.py
- src/plugins/analysis/tlsh/code/tlsh.py
- src/test/unit/helperFunctions/test_hash.py
This PR should (hopefully) make FACT compatible to running Python from a venv.
- converted python package dependencies to pip dependencies 
- updated `tlsh` function for newer version 
- added a test
- bumped hash/tlsh plugin versions
- observation: newer tlsh version is backwards compatible to old hashes and can compute hashes for string lenghts >=50 (old: >=256)
- old tlsh version is not upwards compatible with new hashes (they have a new prefix)
- refactoring
> Virtualenv compat

- src/test/acceptance/rest/test_rest_compare.py
- src/test/acceptance/rest/test_rest_download.py
- src/test/common_helper.py
- src/test/integration/web_interface/rest/test_rest_firmware.py
- src/test/unit/web_interface/rest/test_rest_firmware.py
- src/web_interface/rest/rest_firmware.py
- added default date (`1970-01-01`)
- added validation for release_date field
resolves #687
> rest firmware put bugfix for when release_date is omitted

- src/plugins/analysis/architecture_detection/code/architecture_detection.py
- src/plugins/analysis/architecture_detection/test/test_plugin_architecture_detection.py
Adding TILE* family of architectures.  Not sure if you have a preference on the arch name since `Tilera` is the company name?
> adding the Tilera/TILE-Gx architecture for detection

- src/plugins/analysis/cwe_checker/code/cwe_checker.py
- src/plugins/analysis/cwe_checker/install.py
Switch the Docker image of the cwe_checker plugin to the stable image instead of the latest one. This should hopefully prevent issues like in #691. The downside is that bugfixes to the cwe_checker need longer until they also land in FACT.
> switch to the stable cwe_checker image instead of the latest one

- src/plugins/analysis/elf_analysis/code/elf_analysis.py
- src/plugins/analysis/elf_analysis/test/test_plugin_elf_analysis.py
- src/plugins/analysis/elf_analysis/view/elf_analysis.html
Resolves #700 
- Fixed bug in plugin elf_analysis where `None` is stored in case of no `.modinfo` section
- added check to elf_analysis template so that the server does not crash in case `None` is stored in the DB
- refactoring
> Elf analysis none bugfix

- src/install/requirements_common.txt
- the newly released version 4 of pymongo produces errors with the DB interface
- this fix pins the version to <4
> pin pymongo version

- INSTALL.md
Added instructions specific for WSL (since systemctl is not available on WSL), that make sure that the docker daemon is actually started
> Update INSTALL.md with WSL specific instructions for enabling dockerd

- src/scheduler/Analysis.py
- src/test/unit/scheduler/test_current_analyses.py
- warning log entries will occur during firmware analysis when one file is included in the firmware multiple times
- since this is a common occurrence, the warning is not necessary
- converted the warning log to debug
> converted current analyses duplicate file warning loggings to debug

- src/test/unit/web_interface/test_dependency_graph.py
- src/web_interface/components/analysis_routes.py
- src/web_interface/components/dependency_graph.py
- src/web_interface/static/css/dependency_graph.css
- src/web_interface/static/js/dependency_graph.js
- src/web_interface/templates/dependency_graph.html
Issue #712 made clear that the current dependency graph implementation is of limited use: Usage in larger environments fails due to missing tools for proper navigation. As the client-side code was rather messy and unmaintained, I took this as a chance to completely re-implement the feature with added functionality.
This PR includes following changes:
* Enabled `vis.js` physics using the rather fast [forceAtlas2Based](https://visjs.github.io/vis-network/docs/network/physics.html) solver
* Nodes are no longer draggable (the physics solver will take care of clustering, if even possible in complex dependecy graphs)
* Physics simulation will stop after 60 seconds to save power and CPU cycles (should be sufficient to kind of stabilize the graph)
* Each element in the sidebar is collapsible
* …
> Reimplement dependency graph with tools for navigation

- src/helperFunctions/merge_generators.py
- src/storage/db_interface_backend.py
- src/test/integration/storage/test_db_interface_backend.py
- src/test/unit/helperFunctions/test_merge_generators.py
`parents` field was missing from `FileObject` update method.
This results in the `parents` being overwritten each time the object is updated.
This PR fixes this problem by merging the old parents and new parents instead (similar to the "parent firmware UIDs").
Added a test to make sure this works as intended.
> File object update parents bugfix

- src/storage/db_interface_frontend.py
- src/test/common_helper.py
- src/test/unit/web_interface/test_app_show_analysis.py
- src/test/unit/web_interface/test_dependency_graph.py
- src/web_interface/components/analysis_routes.py
- src/web_interface/components/dependency_graph.py
- src/web_interface/static/js/dependency_graph.js
- src/web_interface/templates/dependency_graph.html
- src/web_interface/templates/show_analysis.html
_This PR is supplementary to PR #726 and a follow-up of PR #725 ._
It fixes the dependency graph to properly display symlinks. Multiple links on a single file (i.e., in busybox-centric environments) produce the same object hash. Thus, FACT aggregates them in a single file object for deduplication and adds a virtual file path reference in the dataset.
As the previously reworked dependency graph created nodes based on file objects instead of virtual file paths, it did not incorporate all nodes existing in the path structure.
This PR fixes this issue.
> Dependency graph: use virtual paths

- src/install/common.py
This is a temporary fix for the pip installation aimed solely at Ubuntu bionic (which is seemingly stuck with Python 3.6 until it reaches End of Life next year).
> temporary fix for outdated python in bionic

- src/plugins/analysis/init_systems/code/init_system.py
- src/plugins/analysis/init_systems/test/test_plugin_init_system.py
Starting a single-file analysis with plugin "init_systems" led to an error, because `file_object.root_uid` was missing in this context.
- fixed missing `root_uid` bug
- pylint fixes
- added test
> Init systems single file analysis bugfix

- src/web_interface/components/analysis_routes.py
- src/web_interface/templates/show_analysis.html
Fixed bug in on "show analysis" page caused by missing root UID (can happen e.g. when coming from a DB search)
```python
{% block body %}{% endblock %}
File "<template>", line 67, in block 'body'
TypeError: can only concatenate str (not "NoneType") to str
```
> fixed error in show_analysis caused by missing root_uid

- src/install/requirements_frontend.txt
See [flask-login issue #636](https://github.com/maxcountryman/flask-login/issues/636).
werkzeug 2.1.0 removes the deprecated 'safe_str_cmp' used by latest pypi flask-login 0.5.0. The main branch has regular updates that solve this problem. We didn't see a pypi package update since Feb 9 2020. For the time being, we could use a git-based install of the main branch, which works perfectly fine.
> update flask-login version

- src/plugins/analysis/elf_analysis/code/elf_analysis.py
- src/plugins/analysis/elf_analysis/test/test_plugin_elf_analysis.py
fixes #753 
Do you guys see any reasons why we shouldn't use `to_json` instead of `to_json_from_abstract`? Tests show that it provides the expected outcome.
> elf_analysis: use lief's to_json instead of to_json_from_abstract

- src/web_interface/static/js/loading.js
- src/web_interface/templates/database/database_search.html
- src/web_interface/templates/upload/upload.html
There was a problem with the loading gif covering the basic search and upload form when going back to the page (e.g. by clicking on the "go back" button in the browser). This should fix this problem.
> hide loading gif when going back in page history

- src/plugins/analysis/linter/apt-pkgs-runtime.txt
- src/plugins/analysis/linter/dnf-pkgs-runtime.txt
- src/plugins/analysis/linter/install.py
- src/plugins/analysis/linter/internal/linters.py
- src/plugins/analysis/linter/test/test_ruby_linter.py
`rubocop` linter installation failed for bionic and buster. This PR should fix this.
- switched to rubocop docker image to fix installation problems on older systems
- pylint fixes
> fixed bug with rubocop linter installation in older systems

- src/install/requirements_backend.txt
This is used in `task_conversion.py`
Also I removed unnecessary comments and one dependency that isn't used anymore.
> backend: Add missing dependency

- src/init_postgres.py
In a distributed setup we would always try to connect to localhost before this change.
> init_postgres.py: Connect to correct host and port

- src/test/common_helper.py
- src/test/unit/web_interface/test_quick_search.py
- src/web_interface/components/database_routes.py
- src/web_interface/templates/base.html
- removed md5 from quick search (it was broken anyway)
- added unit tests for quick search (there weren't any)
- updated placeholder string to better reflect what can be searched for
> Md5 quick search bugfix

- src/helperFunctions/install.py
Fix for pip package installation error handling when `CalledProcessError.stderr` is `None`
> pip package installation error handling bugfix

- src/plugins/analysis/information_leaks/code/information_leaks.py
The current regular expressions in the `information_leaks` path matching fail when the path hierarchy ends after level two, e.g. `/root/.ssh`. Depending on the follow-up characters, the expressions then match either nothing or include non-printable characters. The first edge case is a false-negative. The second edge case parse a corrupted path including non-printable bytes. Since the postgres database doesn't accept such data on `string`-type columns, the backend crashes once analysis results are written to the database. As our old DBMS `mongodb` just swallowed those values, nobody noticed.
> reduce false negative matches in information leaks plugin path matching

- src/install/requirements_frontend.txt
assure that pinned werkzeug version is not overwritten during installation of other dependencies (flask, flask-login, flask-restx) by putting it right at the bottom of the list
> assure that pinned werkzeug version is not overwritten

- src/storage/entry_conversion.py
- src/unpacker/unpack.py
```python
[2022-07-26 11:25:34][process][ERROR]: Exception in Scheduler process:
Traceback (most recent call last):
File "/home/testbed/tools/FACT_core/src/helperFunctions/process.py", line 51, in run
Process.run(self)
File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/home/testbed/tools/FACT_core/src/scheduler/analysis.py", line 267, in _task_runner
self._process_next_analysis_task(task)
File "/home/testbed/tools/FACT_core/src/scheduler/analysis.py", line 271, in _process_next_analysis_task
self.pre_analysis(fw_object)
File "/home/testbed/tools/FACT_core/src/storage/db_interface_backend.py", line 26, in add_object
self.insert_object(fw_object)
File "/home/testbed/tools/FACT_core/src/storage/db_interface_backend.py", …
```
> Add 'plugin_version' key to plugin result when unpacker hits max unpacking depth

- src/storage/entry_conversion.py
- src/storage/schema.py
the DB schema allows `null` values for `AnalysisEntry.result`
While there shouldn't be a Null entries at the moment, such entries would cause errors for stats updates. This is because the stats generation functions use PostgreSQL functions which generally don't work on Null values.
This modification adds a reasonable default value, which should prevent such problems in the future.
> add sensible defaults for anaylsis db entries

- src/plugins/analysis/software_components/signatures/os.yara
Major release 6 is around the corner - we better future-proof our YARA rule :-)
> linux kernel yara rule: exchange [1-5] limit on major release to \d

- src/plugins/analysis/architecture_detection/internal/dt.py
- src/storage/entry_conversion.py
- src/test/unit/storage/test_entry_conversion.py
There may still be errors when storing analysis results in the DB if summary entries contain NULL bytes. This PR should fix this.
> fixed bugs that may occur if summary entries contain NULL bytes

- src/conftest.py
- src/test/common_helper.py
Cherrypicked from #867 
This code should be mergable as it is, as it was already reviewed in #749.
Having this in master allows us to test code using the  `config.py` module (E.g. #850 ).
Since the `config.py` module is already merged in master it makes no sense to only have these two commits in the `config-dev` branch.
> Cherrypick testing code for config.py

- src/plugins/analysis/kernel_config/internal/decomp.py
Fixed a bug in the kernel_config plugin where a `EOFError` could cause the plugin to crash.
resolves #884
> handled EOFError in kernel_config decomp + pylint fixes

- src/plugins/analysis/information_leaks/code/information_leaks.py
- src/plugins/analysis/information_leaks/test/data/path_test_file
- src/plugins/analysis/information_leaks/test/test_plugin_information_leaks.py
- Removed (some) files from info_leaks summary to reduce 'spammyness' of the summary for files containing many matched paths:
- A summary entry is created for each matching path but for some files containing lots of paths this can mean a lot of (mostly) redundant summary entries. This PR tries to reduce this a bit by filtering out file paths obviously ending with a file and only using the parent folder as result
- improved regexes
> removed (some) files from info_leaks summary

- src/analysis/PluginBase.py
- src/analysis/YaraPluginBase.py
- src/compare/PluginBase.py
- src/compare/compare.py
- src/plugins/analysis/architecture_detection/code/architecture_detection.py
- src/plugins/analysis/cve_lookup/test/test_cve_lookup.py
- src/plugins/analysis/elf_analysis/test/test_plugin_elf_analysis.py
- src/plugins/analysis/file_system_metadata/test/test_plugin_file_system_metadata.py
- src/plugins/analysis/hashlookup/test/test_hashlookup.py
- src/plugins/analysis/linter/test/test_source_code_analysis.py
- src/plugins/analysis/qemu_exec/test/test_plugin_qemu_exec.py
- src/plugins/analysis/tlsh/test/test_plugin_tlsh.py
- src/plugins/base.py
- src/plugins/compare/file_coverage/test/test_plugin_file_coverage.py
- src/scheduler/analysis.py
- src/test/unit/analysis/analysis_plugin_test_class.py
- src/test/unit/analysis/test_plugin_base.py
- src/test/unit/compare/compare_plugin_test_class.py
- src/test/unit/compare/test_plugin_base.py
Removed `register_plugin` and `plugin_administrator` constructs where the scheduler class is passed to the plugin so that the plugin can write itself into the list of plugins inside the scheduler, which is both unnecessarily complicated and generally unnecessary.
Instead, this can be done directly inside the scheduler (where the plugins are initialized anyway).
> removed `register_plugin` construct

- src/install/pre_install.sh
bionic installation was broken because the installed nodejs requires a newer glibc version
side note: the node version which is installed for bionic is 14 which will reach its EoL together with bionic in April 2023
> fixed (node) installation for bionic

- .github/workflows/build_ci.yml
do not abort all jobs of the matrix when one failed
> disable fail-fast for ci build matrix

- .github/workflows/build_ci.yml
`schedule` only affects the latest commit of the `default` branch
> add time based ci build at 03:00am UTC each night

- src/test/unit/web_interface/test_app_comparison_text_files.py
- src/web_interface/components/compare_routes.py
- the text file diff page did not support reloading/bookmarking/etc. because the comparison UIDs were taken from the session instead of the URL
- this PR splits the initiation of a text file diff from showing the actual page to fix those problems
> text file comparison from url instead of session

- src/intercom/back_end_binding.py
- src/intercom/front_end_binding.py
- src/test/integration/intercom/test_backend_scheduler.py
- src/test/integration/intercom/test_task_communication.py
- src/test/unit/web_interface/test_app_comparison_text_files.py
- src/web_interface/components/compare_routes.py
- src/web_interface/templates/compare/text_files.html
- moved file_diff functionality from the frontend to the backend (where the files are located)
- this way only one intercom task is needed instead of two and also less data is transmitted (the diff string instead of the contents of the two files)
- added intercom listener for that
-  adjusted intercom response poll delay to stop wasting lots of time
- file_diff load times should be a lot faster (at least twice as fast)
- fixed and added tests
- added escape for three elements that caused errors in the file_diff template:
- str format variables (`${var}`)
- backslashes
- backticks
> file diff optimization and bugfixes

- src/helperFunctions/program_setup.py
- src/start_fact.py
- src/start_fact_frontend.py
- added CLI option to skip radare startup (so radare web GUI won't be available when using this option)
- if radare is not used, this can free up valuable resources
- during development this can speed up startup and shutdown times of FACT significantly
> add CLI option to skip radare startup

- README.md
- docsrc/conf.py
- src/check_signatures.py
- src/compile_yara_signatures.py
- src/flask_app_wrapper.py
- src/install.py
- src/start_fact.py
- src/start_fact_backend.py
- src/start_fact_db.py
- src/start_fact_frontend.py
- src/update_statistic.py
- src/version.py
- src/web_interface/templates/about.html
- src/web_interface/templates/base.html
- Better Code Hub was deprecated at the end of 2022
- All-ish copyright strings replaced
- Added social links to Twitter & Mastodon
> Copyright, Social and bye-bye BCH

- src/scheduler/analysis.py
fixed shutdown of analysis scheduler: there was an unknown syntax error that was unnoticed because of the ThreadPoolExecutor
> fixed shutdown of analysis scheduler

- src/plugins/analysis/input_vectors/test/test_input_vectors.py
The Tests were not actually run before as pytest only auto-discovers tests in classes prefixed with `Test`. [1]
[1] https://docs.pytest.org/en/7.2.x/explanation/goodpractices.html#test-discovery
> plugins/analysis/input_vectors: Fix test name

- docsrc/index.rst
- docsrc/modules/plugins.installer.rst
- docsrc/modules/plugins.rst
- src/install/backend.py
- src/plugins/installer.py
The assumption about the cwd was not clear.
Before this commit running `./src/install.py --backend-docker-images` would not succeed because of the relative path in the software_components plugin.
> installer: Documentation AbstractPluginInstaller

- src/install/requirements_common.txt
- src/install/requirements_frontend.txt
pinned versions of flask-wtf and setuptools to fix recent issues on the CI
- setuptools: to fix recent installation issues (should be unpinned as soon as possible)
- flask-wtf: incompatible to flask-security-too 5.0.2
> pinned versions of flask-wtf and setuptools

- src/storage/db_connection.py
We did not properly escape special characters.
This is exactly what `sqlalchemy.URL` is for.
Closes #958
> storage/db_connection: Fix engine url

- pyproject.toml
- pytest.ini
a fully populated installation directory with (compose-env, john, node_modules, etc.) can make pytest test discovery slow -> ignore more paths
> fix slow pytest test discovery by ignoring more paths

- src/analysis/PluginBase.py
- src/analysis/YaraPluginBase.py
- src/scheduler/analysis.py
- src/start_fact_backend.py
the system version in `YaraBasePlugin` is no valid version according to [PEP 440](https://peps.python.org/pep-0440/) because it contains an underscore. This in turn causes an `InvalidVersion` exception in newer versions of packaging. This PR replaces the underscore with a dash (which makes it valid). Also fixes this in the analysis scheduler where old versions from the DB are checked (which may still contain underscores).
> yara plugin system version bugfix

- src/web_interface/components/io_routes.py
pydantic populates the class `config.data_storage`. Iterating over it will yield tuples rather than the dictionary keys as before.
> web_interface: Fix analysis presets

- src/web_interface/file_tree/file_tree.py
There can still be files missing from the file tree on the analysis page under certain circumstances:
- if no root_uid is provided (e.g. when coming to the analysis page from a file search)
- and if the file in the file tree is also contained in another FW (i.e. if there are multiple keys in the virtual file path dict)
- and if any of the other FWs does not contain the parent file in the file tree we are looking at
because the root_uid is selected at random if it is missing. 
This PR adds an "educated guess" to make sure that we select a root_uid from a FW that contains the parent file from the file tree we are currently looking at.
> missing files in file tree w/o root_uid fix

- .gitignore
- src/install/frontend.py
- src/web_interface/file_tree/file_tree.py
older versions (<jammy) of the papirus-icon-theme package don't include a dedicated inode-symlink icon, which leads to symlinks being displayed as empty files. This PR fixes this and uses the emblem link icon instead (which is included in all versions from [bionic](https://packages.ubuntu.com/bionic/all/papirus-icon-theme/filelist) to [lunar](https://packages.ubuntu.com/lunar/all/papirus-icon-theme/filelist))
If the icons are already installed, the `src/web_interface/static/file_icons/mimetypes` folder needs to be deleted for the installation to replace the files.
Also removes an unused function that slipped through the review.
> fix for older versions of the icon-theme not providing a inode-symlink icon

- src/plugins/analysis/cve_lookup/code/cve_lookup.py
- src/plugins/analysis/cve_lookup/internal/helper_functions.py
- src/plugins/analysis/cve_lookup/test/test_cve_lookup.py
Improved cve_lookup version comparison which was somewhat broken after the update to the 'packaging' module (which removed the `LegacyVersion` and forced versions to be PEP 440 compliant).
Also reduced log spam if the version cannot be parsed (which looked kind of confusing because the errors were logged with `logging.exception()` which prints traces even though the exception was actually caught).
> improved cve_lookup version comparison

- src/migrate_db_to_postgresql.py
- src/storage/entry_conversion.py
- fixed a bug with tuples in analysis results not being sanatized
- added exception handling for custom classes occurring in pickled ("sanitized") results
- split migration of `FileObject`s and analyses
- the migration should continue if single analyses cannot be migrated
resolves #964
> Migration bugfixes

- src/web_interface/templates/upload/upload_successful.html
- added link to live progress (system health) to the message you receive after a successful upload
- changed text slightly to better reflect, that you can access the analysis page earlier (since the files and results are added immediately when they are ready now in contrast to when the text was written)
> added link to live progress after upload

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/question.yml
You can try them out at [my fork](https://github.com/maringuu/FACT_core/issues).
Blank issues are still allowed, I'm not sure if the templates contain everything we need.
Closes #893
> Add issue templates

- src/plugins/analysis/information_leaks/code/information_leaks.py
- src/plugins/analysis/information_leaks/test/test_plugin_information_leaks.py
For most things (IDE / SDK configs etc.) leaks are already grouped. File paths are stored independently though, making the summary cluttered. These are now also grouped by their categories (user paths, root paths, www paths).
> Consistently store only category of information leak in summary

- .pre-commit-config.yaml
- src/config/main.cfg
- src/scheduler/unpacking_scheduler.py
- src/web_interface/static/js/system_health.js
- src/web_interface/templates/system_health.html
- Unpacking is throttle for larger analysis queues. That was not transparent before
- Fixed pre-commit path for flake8 as sideeffect
> Added indicator to signify that unpacking is halted

- src/helperFunctions/hash.py
- src/test/unit/helperFunctions/test_hash.py
lief is used for imp(ort) hash calculation but can crash with a segfault on broken ELF files which is ... unfortunate during an analysis of the mandatory "hash" plugin and shouldn't happen. This PR replaces lief with the more robust `readelf` which is included in the `binutils` package (which is already installed for the backend). The output should be identical in most cases (so that new hashes should match old ones).
Also removed the now unnecessary `_suppress_stdout` function.
> imphash: replaced lief with readelf

- src/web_interface/static/js/system_health.js
- src/web_interface/templates/system_health.html
- made design of "current analyses" on system health page more consistent with the rest of the page
- removed legend of "current analyses" (should be self-explaining now)
- "current analyses" should be correctly rendered as link now (meaning stuff like "open in tab" should now work)
- switched to bootstrap "table-sm" for most tables on the page to save some vertical space
> updated current analyses design

- src/helperFunctions/plugin.py
The deprecated
[load_module](https://docs.python.org/3/library/importlib.html#importlib.abc.Loader.load_module) did this.
Since we are using `exec_module` which apparently does not update `sys.modules` we have to do it ourselves.
The documentation is not that clear imo. This fix might not be the correct way to do this, but it works fine.
> helperFunctions/plugin: Update `sys.modules`

- src/manage_users.py
- src/test/unit/test_manage_users.py
the more recent version of flask-security-too (?) needs an app context to work
also fixed previously wrongly "fixed" tests that masked the real problem
> manage users bugfix

- src/install.py
the log level of `install.py` was erroneously set to "WARNING" which results in the installation appearing to hang (while it actually runs in the background)
> set default installation log level to INFO

- src/helperFunctions/install.py
- src/test/integration/storage/test_db_interface_frontend.py
- fixed the logging output of the pip package installation (switched to `stdout` because `stderr` is usually empty)
- added an advanced search test for searching in objects (dicts) inside arrays (lists) in `JSONB` columns
- the syntax is not very intuitive and therefore the test also demonstrates how such a search works
- which could be interesting for a structural change of the analysis results of some plugins in the future
> Refactoring and test coverage

- src/plugins/analysis/qemu_exec/code/qemu_exec.py
- src/plugins/analysis/qemu_exec/docker/Dockerfile
- src/plugins/analysis/qemu_exec/install.py
- src/plugins/analysis/users_and_passwords/docker/Dockerfile
updated alpine base image of users_and_passwords and qemu_exec plugins from alpine 3.14 to 3.17 (because 3.14 has reached its end of life)
> updated alpine base image

- src/scheduler/analysis.py
- src/storage/db_interface_common.py
The method `update_analysis_of_object_and_children()` used to fetch every object during an update individually from the database. Switching to `get_objects_by_uid_list()` improves the performance significantly. During a test with a firmware with ~1.7k files, this reduced the time to schedule the objects from ~58 seconds to ~2.2.
> sped up analysis update by using a more efficient DB method

- src/scheduler/unpacking_scheduler.py
- src/unpacker/extraction_container.py
- src/unpacker/unpack.py
- src/unpacker/unpack_base.py
`ConnectionError`s mostly appear in tests because the docker container is not yet ready for accepting extraction requests
> extractor: added retry to mitigate connection errors

- .pre-commit-config.yaml
- pyproject.toml
pylint has become so slow on modules like sqlalchemy that it is almost unusable. "ruff" is a linter written in Rust that can replace many checks of popular python linters and is lightning fast. The downside: it does not implement *all* checks that pylint does. On the upside it includes more checks from other linters we did not previously use like bugbear. Other not included  pylint checks 
are covered by included flake8 extensions. On the whole, it extends the linting capabilities and adds some new interesting checks.
- added ruff pre-commit hook (incl. auto-fix)
- removed pylint, isort and flake8 hooks (mostly replaced by ruff)
- updated version of black hook (to address warning)
- added toml check hook
- updated python version (to reflect removal of python 3.7 support #1024 )
- added …
> added ruff pre-commit hook and removed flake8 and pylint

- src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
- src/plugins/analysis/users_and_passwords/install.py
- src/plugins/analysis/users_and_passwords/test/test_plugin_password_file_analyzer.py
There was a problem in the `users_and_passwords` analysis plugin: If the password hash could not be cracked, it was displayed as "hash type is not supported" in the result. This PR adds differentiation between the cases where the hash is not supported and the cases where it couldn't be cracked.
- fixed docker image label
- added test cases to test differentiation
> User and pw fail fix

- src/plugins/analysis/software_components/code/software_components.py
- src/plugins/analysis/software_components/signatures/00_meta_filter.yara
- src/plugins/analysis/software_components/signatures/crypto.yara
- src/plugins/analysis/software_components/test/test_plugin_software_components.py
- fixed a bug where OpenSSL versions like OpenSSL 0.9.8zh were detected as 0.9.8z
- fixed a bug where software versions like 1.1.0i (e.g. OpenSSL) were detected as 1.1.i
- fixed a bug where text files were matched with "no_text_file" signatures because of their MIME type (text/html instead of text/plain)
- refactoring and ruff fixes
> Software components bugfixes

- .github/workflows/build_ci.yml
- src/install/pre_install.sh
* set `Dpkg::Options::="--force-confnew"` apt-get option to automatically accept a new configuration during the docker installation
* the installation (and the CI) will hang otherwise, waiting for manual input
* reduce timeout from 45 to 35 min (the CI should not run much more than 25 min even if all workers are busy)
> hanging CI action fix

- src/unpacker/extraction_container.py
fixed bug where an unpacking container timeout during get leads to multiple extractions because of a retry
> unpacking: retry bugfix

- .github/workflows/ruff.yml
While it is not that popular according to github stars it is the one mentioned in the official docs.
https://beta.ruff.rs/docs/usage/#github-action
> github: Add ruff action

- src/test/unit/web_interface/test_filter.py
- src/web_interface/filter.py
* fixed sorting of cve_lookup results
* the results were erroneously sorted alphabetically instead of numerically (resulting in score 1<10<2)
* changed sorting key so that the results are also sorted by CVSS v3 score (instead of v2 score only)
* added test cases
* ruff fixes
> CVE lookup result sort fix

- src/analysis/YaraPluginBase.py
- src/test/unit/analysis/test_yara_plugin_base.py
- fixed a YARA meta parsing bug caused by single quotes in metadata strings
- YARA apparently inserts backslashes before single quotes in metadata strings (even though the strings themselves use double quotes)
- the YAML parser does not like that ("unknown escape")
- changed the parsing test so that it replicates the problem
> fixed a yara meta parsing bug

- src/web_interface/components/analysis_routes.py
fixed a `KeyError` that occurs during update preset generation when a plugin is removed (but the DB entry of the FW contains an analysis result of that plugin)
> update preset `KeyError` fix

- src/storage/db_interface_common.py
- src/storage/entry_conversion.py
- src/storage/schema.py
- src/test/integration/storage/test_db_interface_backend.py
- src/test/unit/web_interface/test_app_jinja_filter_static.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/file_tree/file_tree.py
`FileObject.parent_firmware_uids` is set based on `virtual_file_path` which worked in the past, because the keys were the root FW UIDs. Now however, the keys are the parent container UIDs and the contents of `FileObject.parent_firmware_uids` are therefore wrong. This causes some VFP-related bugs in the frontend.
> More vfp fixes

- src/analysis/plugin/plugin.py
The idea here as to have the symmetry that when result is None the tags would also be None.
While I like this in general this was not thought out. The get_tags signature did not allow this and the rest of the codebase was not build with this in mind.
> fix(plugins): Don't crash when result is None

- src/manage_users.py
the default config in the `manage_users.py` script still used the old config file name as default value
> manage_users: default config name fix

- src/analysis/plugin/plugin.py
- src/config.py
- src/conftest.py
- src/install/requirements_backend.txt
- src/install/requirements_frontend.txt
- src/plugins/analysis/file_system_metadata/test/test_file_system_metadata_routes.py
- src/plugins/analysis/qemu_exec/test/test_routes.py
- src/plugins/compare/file_header/code/file_header.py
- src/plugins/compare/file_header/test/test_file_header.py
- src/test/conftest.py
- src/test/integration/web_interface/rest/base.py
- src/test/integration/web_interface/rest/test_rest_binary.py
- src/test/integration/web_interface/rest/test_rest_statistics.py
- src/test/unit/compare/compare_plugin_test_class.py
- src/test/unit/compare/test_plugin_base.py
- src/test/unit/web_interface/test_plugin_routes.py
[The last scheduled master CI build](https://github.com/fkie-cad/FACT_core/actions/runs/5995159722/job/16257774384) had 43624 warnings when running the tests. This PR should reduce this number to less than 30. There are some warnings that can't be fixed because they are caused by dependencies or where it is too complicated (the crypto_hints plugin should be fixed in its own PR).
> Fix deprecation warnings

- src/install/requirements_backend.txt
fixes dependency version conflict caused by `cryptography==41.0.3` being installed in `requirements_backend.txt` and `pyopenssl==22.1.0` from the same file depending on 38.0.0<=cryptography<39
> updated pyopenssl version to fix dependency version conflict

- src/plugins/analysis/dummy/routes/routes.py
- src/plugins/analysis/file_system_metadata/code/file_system_metadata.py
- src/plugins/analysis/file_system_metadata/routes/ajax_view.html
- src/plugins/analysis/file_system_metadata/routes/routes.py
- src/plugins/analysis/file_system_metadata/test/test_file_system_metadata_routes.py
- src/plugins/analysis/file_system_metadata/test/test_plugin_file_system_metadata.py
- src/plugins/analysis/file_system_metadata/view/file_system_metadata.html
- src/plugins/analysis/qemu_exec/routes/routes.py
- src/plugins/analysis/qemu_exec/test/test_routes.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/components/plugin_routes.py
- src/web_interface/filter.py
- src/web_interface/rest/rest_resource_base.py
* migrated plugin "file_system_metadata" to new "V0" base class
* fixed bugs caused by result structure changes (`['result']`) in plugin rest routes of fs_metadata and qemu_exec
* fix and refactoring for plugin rest endpoint detection and initialization
> Fs metadata plugin v0

- src/analysis/PluginBase.py
- src/helperFunctions/process.py
- tracebacks from analysis exceptions were printed to the command line but not logged, resulting in them not showing up in log files or the web GUI
- this only affected the old plugin base class but not the new base class / runner
- added a parameter `reraise` to `ExceptionSafeProcess` so that the trace is only printed once
> tracebacks from analysis exceptions are now logged

- src/config/fact-core-config.toml
- src/plugins/analysis/cwe_checker/code/cwe_checker.py
- adds an option for configuring a memory limit for the `cwe_checker` plugin
- sets a default value of 4GB
> cwe-checker: add memory limit

- src/test/integration/web_interface/rest/test_rest_firmware.py
- src/web_interface/rest/rest_firmware.py
- fixes a bug in route /rest/firmware put when submitting a firmware with unavailable plugins in `'requested_analysis_systems'`
- the "requested_analysis_systems" were not validated previously, leading to a `KeyError` during scheduling
resolves #1147
> rest put firmware: unknown plugin fix

- src/web_interface/filter.py
- sort tags on analysis page
- to fix the problem that the order of displayed tags is random and switches around when you reload the page
> sort tags on analysis page

- src/scheduler/unpacking_scheduler.py
- src/storage/db_interface_backend.py
- src/test/integration/storage/test_db_interface_backend.py
- Handle the exception that occurs when trying to upload a file as firmware that is already in the DB as included files of another firmware
- log error instead of passing the file to the analysis scheduler
- this should handle the exceptions from #1149 and #1145
> handle exception when part of a fw is reuploaded as fw

- src/test/integration/web_interface/test_filter.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/filter.py
- src/web_interface/static/js/show_analysis_summary.js
- src/web_interface/templates/generic_view/tags.html
- src/web_interface/templates/show_analysis.html
- src/web_interface/templates/summary.html
- Analysis tags can be clicked and link to the summary of the analysis (which set the tag)
- The summary is loaded automatically (only if a tag was clicked, not always)
- fixed a bug in the summary for file objects
> Clickable analysis tags

- src/plugins/analysis/cwe_checker/code/cwe_checker.py
- removes objects of the type `application/x-object` from the MIME whitelist of the CWE Checker plugin because they are not supported
> cwe-checker: remove incompatible type x-object from whitelist

- src/install/requirements_frontend.txt
- src/install/requirements_pre_install.txt
I'm pretty confident that this fixes #1144. I experienced the same behavior described there (i.e. slow uploads of large files, but only when performed via the web UI). Updating to werkzeug 2.3.8 fixed the issue.
#1153 will also address this problem, but since there's no ETA on when a compatible flask-restx will be released, I think it makes sense to bump to 2.3.8 in the meantime. The slow multipart parsing is [the only change 2.3.8 contains](https://github.com/pallets/werkzeug/pull/2804), so there should be no compatibility problems.
> Bump werkzeug to 2.3.8 to fix slow uploads of large files via the UI

- src/install/pre_install.sh
The `setup_lts.x` script [has been deprecated](https://github.com/nodesource/distributions). 
> The installation scripts setup_XX.x are no longer supported and are not needed anymore, as the installation process is straightforward for any RPM and DEB distro.
This PR modifies `pre_install.sh` to use the new repo setup method. I used the 18 LTS repo since that's the one the original script set up.
> Replace deprecated nodejs repo setup with updated method

- .github/ISSUE_TEMPLATE/bug-report.yml
Bug reports without the option to give information about the ovserved behavior are pretty useless.
> chore: Update bug report template

- src/fact_base.py
- src/install/requirements_common.txt
- log fact version, git commit hash and python version on startup of each component
- should help debugging some of the bare logs we get in GitHub issues
> print out fact version + git hash on start

- src/helperFunctions/task_conversion.py
- src/test/unit/helperFunctions/test_task_conversion.py
The [werkzeug `FileStorage` object](https://werkzeug.palletsprojects.com/en/2.3.x/datastructures/#werkzeug.datastructures.FileStorage) provides a `stream` to the underlying bytes, so there's no need to save it to disk to read out the bytes.
> Remove unnecessary saving of uploaded file to tmp dir

- src/install/backend.py
- src/install/requirements_common.txt
Addressing an old `FIXME` in `requirements_common.txt`
That said, 4.5.0 was released [two days after 4.4.0](https://pypi.org/project/yara-python/#history) and has [a bunch of bug fixes](https://github.com/VirusTotal/yara/releases/tag/v4.5.0); should the version be updated to that instead?
> Update yara and yara-python to 4.5.0

- src/plugins/analysis/crypto_hints/code/crypto_hints.py
- src/plugins/analysis/crypto_hints/test/test_crypto_hints.py
- src/plugins/analysis/crypto_hints/view/crypto_hints.html
> crypto hints: Use plugin.PluginV0

- src/plugins/analysis/architecture_detection/internal/dt.py
- src/plugins/analysis/architecture_detection/test/test_plugin_architecture_detection.py
- fixes a bug in the `dt` module of the `cpu_architecture` plugin introduced by changing the result structure of the `device_tree` plugin in #1028 
the bug:
```python
File "src/plugins/analysis/architecture_detection/internal/dt.py", line 81, in construct_result
dt = dt_dict['device_tree']
~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'device_tree'
```
> cpu arch plugin: device tree result changes bug fix

- src/install/frontend.py
- src/web_interface/file_tree/file_tree.py
- file tree: added dedicated icon for linux kernel image files
> file tree: linux kernel image icon

- docsrc/conf.py
- src/helperFunctions/magic.py
- src/install/common.py
- src/install/internal_symlink_magic
- src/install/requirements_common.txt
- src/plugins/analysis/file_type/code/file_type.py
- src/plugins/analysis/qemu_exec/code/qemu_exec.py
- src/test/acceptance/test_io_routes.py
- src/test/integration/helperFunctions/test_pdf.py
- src/test/unit/helperFunctions/test_magic.py
- src/unpacker/unpack.py
- src/web_interface/components/io_routes.py
This uses https://github.com/maringuu/fact-mime-database which is imo the only relevant thing that fact_helper_file provides.
Before merging we should somehow incoperate that fact_helper_file/mime/custom_mime_internal is missing.
If would be great if we could add this somehow add to the FACT_core repo to make fact-mime-database not use its generality.
> refactor: Drop dependency on fact_helper_file

- src/plugins/analysis/file_system_metadata/routes/ajax_view.html
- src/plugins/analysis/file_system_metadata/routes/routes.py
- src/plugins/analysis/file_system_metadata/test/test_file_system_metadata_routes.py
When an unpacked and analyzed file has the same name across firmware images, the `file_system_meta_data` plugin did not show the results for all firmware images in the file object view.
> Bugfix: file_system_meta_data did not show all results for a file object across firmwares

- src/install/frontend.py
- src/install/pre_install.sh
- src/install/requirements_frontend.txt
- src/install/requirements_pre_install.txt
Updated nodejs version from 18 to 22 ([18 is no longer actively supported](https://endoflife.date/nodejs)). Installing nodejs with nodeenv has the advantage that the installed nodejs cannot clash with a possible pre-installed version in the system. What is more, it makes the installation easier (especially updating and changing the version).
> unify nodejs installation with nodeenv

- src/storage/db_connection.py
- removed unnecessary user/pw parameters from db connection constructor
resolves #1035
> Simplify db connection constructor

- src/helperFunctions/install.py
- src/init_postgres.py
- src/install/db.py
- src/test/conftest.py
- update postgres from 14 to 17
- also fixed bugs:
- fixed a bug in the init postgres script when the local postgres instance does not run on the default port
- fixed a copy&paste bug in a test fixture
> Update postgres to v17

- .markdownlint.yaml
- .pre-commit-config.yaml
- README.md
With @jstucke
- Updated information in README
- Restructered README for better navigation and clarity
- Added up-to-date motivation section at the top
> Improved README

- src/analysis/plugin/plugin.py
- src/helperFunctions/hash.py
- src/plugins/analysis/hash/code/hash.py
- src/plugins/analysis/hash/test/test_plugin_hash.py
- src/plugins/analysis/hash/view/hash.html
- src/test/unit/helperFunctions/test_hash.py
- fixed a bug in AnalysisPluginV0 (summarize should not be abstract, since the summary is optional)
- migrated the hash plugin to the new base class
> Hash plugin v1

- src/storage/migration/versions/6a1c50ade0f3_added_docstrings.py
- src/storage/schema.py
- added table and column comments for documentation purposes and for displaying in the GraphiQL docs
ToDo:
> postgres comments

- src/test/unit/statistic/test_analysis_stats.py
- the test recently started to fail on the CI, but, for whatever reason, only on the bookworm worker
- this should fix this problem by increasing the timeouts and only needing the test to pass one out of three tries
> fix for flaky test_update_duration_stats test

- src/plugins/analysis/crypto_material/code/crypto_material.py
- src/plugins/analysis/crypto_material/internal/key_parser.py
- src/plugins/analysis/crypto_material/test/test_plugin_crypto_material.py
- src/plugins/analysis/crypto_material/view/crypto_material.html
- converted `crypto_material` plugin to new base class
> crypto material plugin v1

- src/test/unit/web_interface/test_filter.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/filter.py
- src/web_interface/templates/show_analysis.html
- preview of certain files were not shown as text (e.g. javascript and json)
resolves #1311
> text preview fix

- src/plugins/analysis/ip_and_uri_finder/code/ip_and_uri_finder.py
- src/storage/db_interface_backend.py
- fixed plugin `ip_and_uri_finder` system version (was unintentionally set to  `None`)
- fixed system version not being set when analysis entries are updated
> System version fixes

- src/intercom/back_end_binding.py
- src/intercom/common_redis_binding.py
- src/intercom/front_end_binding.py
- src/scheduler/analysis/scheduler.py
- src/scheduler/analysis_status.py
- src/scheduler/unpacking_scheduler.py
- src/test/integration/intercom/test_backend_scheduler.py
- src/test/integration/intercom/test_task_communication.py
- src/test/unit/conftest.py
- src/test/unit/scheduler/test_analysis_status.py
- src/test/unit/scheduler/test_unpack.py
- src/test/unit/web_interface/test_app_ajax_routes.py
- src/web_interface/components/ajax_routes.py
- src/web_interface/security/privileges.py
- src/web_interface/static/js/system_health.js
- new feature: cancel analyses that are currently in progress (also works with updates)
- analyses and extractions that are currently underway will not be canceled
- instead, following analyses and extractions will not be scheduled
- can be triggered on the "system health" page in the web interface (REST: TODO)
> cancel analysis

- src/test/unit/web_interface/test_app_show_analysis.py
- src/web_interface/components/analysis_routes.py
- if an analysis did not run for a file, the user is directed to an error page (a page empty except for an error message)
- this is not helpful, so this PR changes this behavior as follows: Instead of showing the error page the user is forwarded back to the analysis page (without selected plugin) and the error is displayed as flash message
- steps to (re)produce the error: Go to some file in a FW, run a "single file analysis" and go back to the root object through the link in the "general information" section
> forward to analysis page (missing analysis)

- src/install/requirements_pre_install.txt
- src/plugins/analysis/cve_lookup/install.py
- src/plugins/analysis/cve_lookup/internal/data_parsing.py
- src/plugins/analysis/cve_lookup/internal/database/db_setup.py
- stream all data during cve_lookup installation in order to fix RAM issues on the CI
- also: refactor bulky  add_cve_items method (which got even larger because of the changes)
> fix for cve_lookup installation RAM usage

- src/config/fact-core-config.toml
- src/plugins/analysis/cve_lookup/code/cve_lookup.py
- src/plugins/analysis/cve_lookup/internal/lookup.py
CPEs without version constraints (and therefore also related CVEs) were previously ignored due to the high risk of false positives. This PR adds a config option to enable matching those entries (disabled by default)
resolves #1290
> added config option to allow CVE matches without version constraints

- src/web_interface/static/css/base.css
- src/web_interface/static/js/dark_mode.js
- src/web_interface/static/js/dependency_graph.js
- src/web_interface/static/js/fact_statistics.js
- src/web_interface/templates/base.html
- dependency graph
- fix node text color in dependency graph for dark mode
- some jshint fixes
- moved the dark mode JavaScript code into its own file (so it can also be used in `dependency_graph.js`)
- GraphQL search
- fixed `<pre>` elements for dark mode
> additional dark mode fixes

- src/web_interface/templates/database/compare_browse.html
A real update might come later, but for now just using the slightly nicer listing from the home / dashboard page to be more consistent with general fact look.
> Update browse comparisons view

- src/helperFunctions/install.py
- src/helperFunctions/yara_binary_search.py
- src/install/backend.py
- src/install/requirements_common.txt
- src/intercom/back_end_binding.py
- src/intercom/front_end_binding.py
- src/test/data/yara_magic.yara
- src/test/integration/intercom/test_backend_scheduler.py
- src/test/integration/intercom/test_task_communication.py
- src/test/unit/analysis/test_addons_yara.py
- src/test/unit/conftest.py
- src/test/unit/web_interface/rest/test_rest_binary_search.py
- src/test/unit/web_interface/test_app_binary_search.py
- src/web_interface/components/database_routes.py
- src/web_interface/rest/rest_binary_search.py
* [install yara-python from source](https://github.com/fkie-cad/FACT_core/commit/ecafc7c6d54d7d6840a9dfefd2f9425d7c96680f)
* Why ist this necessary? Plugins like software_components need support for YARA modules (especially magic) and the pre-built version of yara-python from PyPI does not include this
* [moved get_yara_error method to backend (intercom)](https://github.com/fkie-cad/FACT_core/commit/700adcad062220f8cb9360dbdde237082e31c6e9)
* having the method in the frontend does not make a lot of sense, because the yara version of the backend could be different and compiling the rules could still fail
> Yara python fix

- src/intercom/back_end_binding.py
- src/intercom/common_redis_binding.py
- src/intercom/front_end_binding.py
- src/objects/file.py
- src/scheduler/analysis/scheduler.py
- src/test/integration/intercom/test_task_communication.py
- src/test/unit/web_interface/test_app_show_analysis.py
- src/web_interface/components/analysis_routes.py
- src/web_interface/static/js/show_analysis_single_update.js
- src/web_interface/templates/analysis_plugins/general_information.html
- src/web_interface/templates/show_analysis.html
- makes intercom backend listener "responder" asynchronous (so it does not block when waiting for the result)
- converts the "single file analysis task" listener into a responder
- changes the show analysis page so that single file analyses are awaited and the page is automatically reloaded
- adds a button to the "analysis is outdated" message to quickly update it
> wait for single file analysis (update)

- docsrc/conf.py
- src/install/requirements_backend.txt
- src/install/requirements_common.txt
- src/install/requirements_frontend.txt
- src/install/requirements_pre_install.txt
- src/plugins/analysis/file_system_metadata/test/test_plugin_file_system_metadata.py
- src/test/integration/scheduler/test_regression_virtual_file_path.py
- src/test/unit/helperFunctions/test_process.py
- src/test/unit/statistic/test_analysis_stats.py
* replaced flaky with pytest-rerunfailures (flaky does not work with newer versions of pytest)
* removed redundant dependencies
> chore: updated pip dependencies

- src/web_interface/components/miscellaneous_routes.py
- src/web_interface/security/decorator.py
removes role requirements from root `/` (home) endpoint to fix redirect loop for users without roles when authentication is enabled. The user still needs to log in to view the page, though.
resolves #1353
> fix: fix for redirect loop in case of user w/o roles

- src/plugins/analysis/ip_and_uri_finder/view/ip_and_uri_finder.html
- src/test/unit/web_interface/test_filter.py
- src/web_interface/components/jinja_filter.py
- src/web_interface/filter.py
* fixed order of keys ('interesting' URIs -> URIs -> IPv4 -> IPv6)
* sorted results
* don't display 'interesting' URIs twice (also in URIs)
> feat: revised IP&URI template

- src/test/integration/web_interface/test_filter.py
- src/web_interface/templates/generic_view/tags.html
- show pointer cursor for clickable tags for analysis tags on the analysis page
Thanks to @stauchert for the suggestion!
> feat: show pointer cursor for clickable tags

- src/plugins/analysis/cve_lookup/code/cve_lookup.py
- src/plugins/analysis/cve_lookup/test/test_cve_lookup.py
- src/plugins/analysis/known_vulnerabilities/code/known_vulnerabilities.py
- src/plugins/analysis/known_vulnerabilities/internal/rulebook.py
- src/plugins/analysis/known_vulnerabilities/test/data/sc.json
- src/plugins/analysis/known_vulnerabilities/test/test_known_vulnerabilities.py
- src/plugins/analysis/known_vulnerabilities/test/test_rulebook.py
- src/plugins/analysis/software_components/code/software_components.py
- src/plugins/analysis/software_components/test/test_plugin_software_components.py
- src/plugins/analysis/software_components/view/software_components.html
- src/storage/db_interface_stats.py
- src/test/integration/statistic/test_update.py
also adjusted known_vuln. and cve_lookup plugins to work with the new result structure
> feat: converted software components plugin to new base class

- src/storage/db_interface_frontend.py
> fix: fix for newest sqlalchemy version 2.0.42 introducing a syntax error
